/**
 * FishCast - i18n string table (da/en)
 * Loaded before app.js; consumed by the global t() helper there.
 */

// ═══════════════════════════════════════════
//  INTERNATIONALISATION (i18n)
// ═══════════════════════════════════════════
const STRINGS = {
  da: {
    // General
    back:'← Tilbage', next:'Næste →', skip:'Spring over →', close:'Luk',
    add:'+ Tilføj', added:'✓ Tilføjet', save:'Gem', cancel:'Annuller',
    reset_btn:'🔄 Start forfra — nulstil alt',
    reset_confirm:'Nulstil alt — lokationer, tidsvinduer og målarter slettes. Er du sikker?',
    show_on_map:'Vis på kort 🗺', rename:'Omdøb',
    update_all:'⟳ Opdater alle data', data_ok:'✓ Data',
    loading:'Henter…', error:'Fejl', details:'Detaljer',
    // Days
    day0:'Søn',day1:'Man',day2:'Tir',day3:'Ons',day4:'Tor',day5:'Fre',day6:'Lør',
    // Months
    month0:'Jan',month1:'Feb',month2:'Mar',month3:'Apr',month4:'Maj',month5:'Jun',
    month6:'Jul',month7:'Aug',month8:'Sep',month9:'Okt',month10:'Nov',month11:'Dec',
    // Welcome
    welcome_tagline:'Din personlige fiskeassistent.',
    welcome_sub:'Angiv dine lokationer og tidspunkter — vi finder det bedste vindue.',
    welcome_setup:'Opsæt mine fiskepladser →',
    welcome_continue:'Fortsæt til dashboard',
    welcome_or:'eller',
    welcome_shortcut:'Find fiskesteder hurtigt — ingen opsætning nødvendig',
    welcome_lucky_title:'Held og lykke',
    welcome_lucky_sub:'Find Danmarks bedste hotspot for en bestemt art',
    welcome_nearby_title:'Find i nærheden',
    welcome_nearby_sub:'Søg fiskepladser inden for en given afstand fra dig',
    attribution:'Vejrdata: Open-Meteo · Tidevand + Lyn: DMI Open Data · Regler: lfst.dk',
    // Availability
    avail_title:'Hvornår kan du fiske?',
    avail_sub:'Angiv dine tilgængelige tidsvinduer',
    avail_window:'Tidsvindow',
    avail_add:'+ Tilføj tidsvindow',
    avail_notice:'ℹ️ Tilføj mindst ét tidsvindow for at fortsætte.',
    time_from:'Fra', time_to:'Til',
    method_label:'Fiskemetode', method_pick:'Vælg en eller flere',
    method_required:'Mindst én metode skal være valgt',
    method_shore:'Fra kyst', method_waders:'Waders', method_boat:'Fra båd',
    fm_shore_hint:'Kystfiskeri / stangfiskeri fra land',
    fm_waders_hint:'Vadefiskeri — bundtype og underdrift vægtes',
    fm_boat_hint:'Bådtur — bølgehøjde og vind vægtes hårdere',
    next_species:'Næste: Målarter →',
    next_choose_art:'Næste: Vælg art →',
    next_choose_start:'Næste: Vælg startsted →',
    edit_time:'Rediger →',
    // Water type
    wt_title:'Hvilken type fiskevand?',
    wt_sub:'Vælg de vandtyper du primært fisker i',
    wt_fact_hd:'Vidste du?',
    wt_fact_body:'Det meste af Danmarks kyst er <em>brakvand</em> — ikke ægte saltvand. Kattegat, Øresund, de danske bælter og Østersøen er alle blandinger af salt- og ferskvand. Kun Nordsøen (Jyllands vestkyst) er rigtigt hav. Det betyder at ferskvandsfisk som gedde og aborre kan leve i mange danske havne og fjorde.',
    wt_most_dk:'Mest i DK',
    wt_fresh_label:'Ferskvand', wt_fresh_sub:'Søer, åer og vandløb',
    wt_brackish_label:'Brakvand', wt_brackish_sub:'Fjorde, bælter, Østersøen',
    wt_salt_label:'Saltvand', wt_salt_sub:'Nordsøen (vestkysten)',
    wt_both_label:'Alt vand', wt_both_sub:'Alle vandtyper',
    wt_salt_hint:'Nordsøen / ægte saltvand (~30–35 ppt)',
    wt_brackish_hint:'Kattegat, Øresund, Bælterne, Østersøen (~5–25 ppt). Blanding af salt- og ferskvandsarter.',
    wt_fresh_hint:'Søer, åer og vandløb (~0 ppt)',
    wt_both_hint:'Varierende vandtype — se stedets beskrivelse',
    wt_salt_label_full:'🌊 Saltvand',
    wt_brackish_label_full:'🌿 Brakvand',
    wt_fresh_label_full:'💧 Ferskvand',
    wt_both_label_full:'🗺 Blandet',
    wt_override:'Klik for at overstyre vandtype',
    wt_override_warn:'⚠️ Overstyrende officielle data',
    // Locations
    loc_title:'Dine fiskelokationer',
    loc_sub:'Søg, browse officielle pladser, eller klik direkte på kortet',
    loc_search_tab:'Søg & Browse', loc_map_tab:'Kort',
    loc_search_ph:'F.eks. Køge, Esbjerg, Silkeborg...',
    loc_popular:'⭐ Populære fiskepladser', loc_nearby_hd:'📍 Fiskepladser i nærheden',
    loc_db_count:'pladser i database',
    loc_empty:'Ingen lokationer tilføjet endnu',
    loc_official:'🎣 Officielt fiskested', loc_custom:'📌 Brugerdefineret spot',
    loc_brackish_note:'🌿 Brakvand — salt- og ferskvandsarter mulige ℹ️',
    loc_in_season:'Ingen aktive arter denne måned',
    // Species
    sp_title:'Hvilke arter fisker du efter?',
    sp_sub:'Vælg dine målarter — scoren tilpasses de valgte arters præferencer',
    sp_show:'Vis fiskeforhold →',
    sp_lucky_btn:'🎲 Find bedste hotspot',
    sp_high_season:'⭐ Høj sæson nu',
    sp_in_season:'✅ I sæson nu', sp_restricted:'⚠️ Med begrænsninger', sp_closed:'🚫 Lukket sæson',
    sp_banned_label:'Fangst forbudt', sp_restricted_label:'Begrænsninger',
    sp_handle:'Brug tang ved håndtering',
    sp_regs_note:'⚠️ Regler er vejledende. Verificér altid på',
    // Dashboard
    dash_best:'🏆 Bedste vindue',
    dash_targets:'🎯 Målarter:',
    dash_no_windows:'Ingen tidsvinduer fundet. Tilføj en tilgængelighed i opsætningen.',
    dash_no_forecast:'Ingen vejrdata — tryk Opdater',
    tab_windows:'📅 Tidsvinduer', tab_seasons:'🐟 Fiskesæsoner', tab_conditions:'🌤 Vejr & Bølger',
    best_hour:'Bedste time:',
    lure_label:'🎨 Agn:',
    your_locs:'📍 Dine lokationer',
    moon_title:'🌙 Månefase i dag',
    lightning_title:'⚡ Lyn-status',
    no_lightning:'Ingen lyn registreret',
    update_lightning:'⟳ Opdater lyn',
    lightning_src:'Kilde: DMI · Sidst 45 min · Kun lyn i Danmark',
    lightning_checked:'Tjekket',
    explanation:'ℹ️ Forklaring',
    sunrise:'Solopgang', sunset:'Solnedgang',
    moonrise:'Måneopgang', moonset:'Månenedgang', culmination:'Kulminering',
    moon_phase_today:'Fase:',
    moon_tip_new:'🌑 Nymåne — vandstanden ændrer sig mest (springflod). Fiskene er ekstra aktive; de bedste majortider falder tæt på solop- og nedgang.',
    moon_tip_full:'🌕 Fuldmåne — stærkeste solunareffekt. Springflod giver kraftige strømme og aktive fisk. Især natfiskeri kan være fremragende.',
    moon_tip_quarter:'🌓 Kvartmåne — neapflod med svagere strøm. Fiskene er mindre aktive end ved ny- og fuldmåne, men solaktive perioder virker stadig.',
    moon_tip_gibbous:'🌔 Gibbøs måne — næsten fuld/ny. Aktiviteten stiger — fiskenes appetit tiltar efterhånden som månecyklussen nærmer sig sit højdepunkt.',
    no_windows_empty:'Ingen tidsvinduer. Tjek din tilgængelighed.',
    no_locs_empty:'Ingen lokationer.',
    data_missing:'Ingen vejrdata',
    load_data_btn:'Hent vejrdata', load_data_for:'Hent data til', load_data_missing:'lokationer mangler vejrdata',
    // Hardcoded strings
    locs_ready:'lokationer klar', locs_failed:'fejlede',
    invalid_window:'Ugyldigt tidsvindue',
    no_official_spots:'Ingen officielle fiskesteder inden for 40 km',
    wt_salt_opt:'🌊 Saltvand (~33 ppt)', wt_brackish_opt:'🌿 Brakvand (fjorde, bælter, Østersøen)', wt_fresh_opt:'💧 Ferskvand (søer, åer)',
    lightning_strikes_near:'lynnedslag i',
    sf_no_spots_found:'Ingen pladser fundet', sf_no_spots_db:'i databasen', sf_no_spots_radius:'inden for',
    sf_try_broader:'Prøv en bredere søgning, eller tilføj din lokation manuelt via 📍 Lokationer → Kort.',
    sf_score_hint:'Pladsscore baseret på art, sæson og habitat — vejrdata hentes efter du tilføjer stedet',
    score_lightning_name:'Lynsikkerhed', score_lightning_desc:'Aktive lynslag inden for 10 km sætter scoren til maks 15 og viser rød advarsel. Kulstofstænger er lynledere — gå aldrig ud.',
    // Score modal factors
    fac_pressure_name:'Lufttryk trend', fac_pressure_desc:'Stigende tryk → fiskene aktiveres og jager aktivt. Faldende tryk → de trækker sig mod bunden. Den vigtigste enkeltfaktor.',
    fac_solunar_name:'Solunare perioder', fac_solunar_desc:'Månens kulminering (overhead/underfoot) giver de største aktivitetsperioder. Major perioder = +30 point, minor (op/ned) = +15.',
    fac_timeofday_name:'Tidspunkt på dagen', fac_timeofday_desc:'Daggry (±1t solopgang) er bedst (+20). Skumring er næstbedst (+15). Middag giver straf (−10). Nattefiskeri er neutralt.',
    fac_tide_name:'Tidevand', fac_tide_desc:'Kun ved saltvand. Stigende tidevand aktiverer kystfisk markant. Hentes fra DMIs officielle tidevandsdata for nærmeste station.',
    fac_wave_name:'Bølgehøjde', fac_wave_desc:'< 0.3m: ideelt (+5). 0.6–1m: straf (−6). > 1m: stor straf. Arter som Pighvar foretrækker let bølgegang — tilpasses af artsmål.',
    fac_wind_name:'Vind', fac_wind_desc:'Svag vind (< 3 m/s) giver +7. Over 8 m/s giver −18. Stigende vind straffes ekstra. Vindretning påvirker også (V/VNV = bedst).',
    fac_cloud_name:'Skydække', fac_cloud_desc:'Overskyet (> 65%) giver +8 point. Fisk er mere aktive i diffust lys — de er sværere at se og jager mere frit.',
    fac_precip_name:'Nedbørschance', fac_precip_desc:'> 65% nedbørschance tolkes som tordenvejrsrisiko og straffes hårdt (−20). Desuden frarådes fiskeri med kulstofstænger ved lyn.',
    fac_moon_name:'Månefase', fac_moon_desc:'Ny- og fuldmåne giver ekstra aktivitet (+15). Halvmåne giver +5. Beregnes astronomisk for præcis dato og position.',
    fac_species_name:'Artspræferencer', fac_species_desc1:'Bonus for dine valgte målarter:', fac_species_desc2:'Scoren øges når betingelserne matcher artens specifikke præferencer.',
    fac_spot_name:'Spotrelevans', fac_spot_desc:'Bonus hvis fiskepladsen har dine målarter registreret som aktive denne måned (fra fishingindenmark.info). Officielle stedsdata.',
    score_modal_intro:'Scoren (0–100) samler alle vejr-, astronomiske og stedsspecifikke faktorer til én letlæselig anbefaling.',
    score_modal_legend:'80+ = Fremragende · 65–79 = Godt · 45–64 = Middel · under 45 = Dårligt.',
    score_breakdown_for:'📊 Faktisk pointfordeling for:', score_total:'Samlet score', factor_explain:'Faktorforklaring',
    up_to:'op til', points:'point',
    score_modal_tip:'💡 Vælg målarter i opsætningen for endnu mere præcise anbefalinger.',
    understood:'Forstået',
    // Misc UI
    species_step_notice:'ℹ️ Vælg ingen arter for en generel anbefaling, eller vælg en eller flere for målrettet scoring.',
    selected_label:'Valgte:',
    no_species_selected:'Ingen valgt — søger alle arter',
    click_remove:'Klik for at fjerne',
    customize_open:'+ Tilpas ▼', customize_close:'Luk ▲',
    no_active_nearby:'Ingen aktive arter denne måned nærved',
    estimate_based:'Estimat baseret på:', estimate_from:'Estimat fra:',
    found_count:'fundet',
    best_hotspots:'🏆 Bedste hotspots',
    closed_active:'fredning aktiv',
    // Solunar / astronomy labels
    moon_lbl_new:'Nymåne', moon_lbl_waxing:'Tiltagende', moon_lbl_quarter:'Halvmåne', moon_lbl_full:'Fuldmåne', moon_lbl_waning:'Aftagende',
    sol_culm:'Månens kulminering', sol_under:'Månens lavpunkt', sol_rise:'Måneopgang', sol_set:'Månenedgang', sol_approach:'Nærmer sig månens periode',
    tod_dawn:'Daggry (topaktivitet)', tod_dusk:'Skumring (god aktivitet)', tod_night:'Nat', tod_midday:'Midt på dagen (lav aktivitet)',
    // Score breakdown factors & tags
    bd_pressure:'Lufttryk', bd_pressure_hint:'Lufttryk trend påvirker fiskenes aktivitetsniveau',
    bd_solunar:'Solunar', bd_solunar_none:'Ingen aktiv solunar periode', bd_solunar_hint:'Månens position bestemmer fiskenes aktivitetscyklus',
    sol_major_word:'major', sol_minor_word:'minor', sol_tag_hint:'periode — fiskene er markant mere aktive',
    bd_timeofday:'Tidspunkt', bd_timeofday_none:'Ingen særlig dag-aktivitet', bd_timeofday_hint:'Tidspunkt relativt til solopgang/solnedgang',
    bd_cloud:'Skydække', cloud_word:'skydække', bd_cloud_hint:'Overskyet (>65%) giver +8 — fisk jager friere i diffust lys',
    tag_overcast:'☁ Overskyet', cloud_tag_hint:'fisk jager mere aktivt',
    bd_wind:'Vind', bd_wind_hint:'Svag vind er ideelt; stærk vind gør fiskeri vanskeligt',
    tag_wind_light:'💨 Svag vind', wind_light_word:'Svag vind', wind_ideal:'ideelle forhold',
    tag_wind_strong:'💨 Stærk vind', wind_strong_word:'Stærk vind', wind_difficult:'vanskelige forhold',
    bd_precip:'Nedbør', precip_word:'nedbørschance', bd_precip_hint:'>70% = tordenvejrsrisiko, straffer hårdt',
    tag_thunder:'🌧 Risiko for tordenvejr', thunder_tag_hint:'tordenvejrsrisiko, kulfiberstænger tiltrækker lyn!',
    bd_windtrend:'Vindtrend', windtrend_worse:'Stigende vind forværrer betingelserne gradvist', windtrend_better:'Aftagende vind forbedrer betingelserne',
    windtrend_tag_rising:'Vinden stiger', windtrend_tag_falling:'Vinden aftager',
    windtrend_over3h:'m/s over 3 timer — betingelserne', windtrend_worsen:'forværres', windtrend_improve:'forbedres',
    bd_winddir:'Vindretning', wind_suffix:'-vind', bd_winddir_hint:'V/VNV = bedst; NØ/Ø = ugunstig (gammel fiskeviden)',
    unfavourable:'ugunstig', winddir_tag_hint:'anses traditionelt for ugunstig for fiskeri',
    bd_wave:'Bølgehøjde', wave_word:'bølger', wave_height_word:'bølgehøjde',
    wave_danger:'Farlig sø', wave_high:'Høj sø', wave_calm_lbl:'Blik',
    wave_danger_hint:'farlige forhold, frarådes kraftigt', wave_high_hint:'vanskelige betingelser',
    wave_care_hint:'let forsigtighed anbefales ved vadefiskeri', wave_calm_hint:'næsten blikstille, ideelt for alle metoder',
    bd_method:'Fiskemetode', at_word:'ved', bd_method_hint:'Ekstra vægtning for valgt fiskemetode',
    bd_tide:'Tidevand', tide_rising_word:'↑ Stigende', tide_falling_word:'↓ Faldende', tide_none:'Ingen tidevand',
    bd_tide_hint:'Stigende tidevand aktiverer kystfisk markant',
    tide_tag_rising:'Stigende tidevand ved', tide_tag_falling:'Faldende tidevand ved',
    tide_activates:'aktiverer kystfisk', tide_moderate:'moderat aktivitet',
    bd_moon:'Månefase', bd_moon_hint:'Ny- og fuldmåne giver ekstra aktivitet',
    bd_lightning:'Lynrisiko', thunder_risk:'Tordenvejrsrisiko', bd_lightning_hint:'Høj nedbørschance = mulig tordenvejr, ekstra straf',
    bd_species_hint:'Betingelserne matcher dine valgte målartes præferencer',
    // Toasts / connectivity
    toast_fetch_failed:'Kunne ikke hente vejrdata til', toast_retry:'Prøv igen',
    toast_offline:'Du er offline — vejrdata kan ikke hentes', toast_back_online:'Online igen — opdaterer vejrdata…',
    toast_refreshing_stale:'Opdaterer forældede vejrdata…',
    // Setup sharing
    setup_share_btn:'📤 Del min opsætning', setup_link_copied:'✓ Link kopieret — send det til en fiskemakker',
    setup_shared_title:'Delt opsætning', setup_shared_intro:'En anden FishCast-bruger har delt deres opsætning med dig:',
    setup_import:'Importér opsætning', setup_import_warn:'Erstatter dine nuværende lokationer, målarter og tidsvinduer.',
    setup_sum_locs:'lokationer', setup_sum_species:'målarter', setup_sum_slots:'tidsvinduer',
    topbar_species:'🎯 Målarter', topbar_locations:'📍 Lokationer', topbar_times:'⏱ Tidsvinduer',
    save_back_dash:'Gem og tilbage til dashboard',
    // Score labels
    score_excellent:'Fremragende', score_good:'Godt', score_avg:'Middel',
    score_below:'Under middel', score_poor:'Dårligt',
    // Score info modal
    score_modal_title:'📊 Fiskeindeks — forklaring',
    score_modal_base:'Basisværdi for alle vinduer',
    score_breakdown_title:'Score-fordeling bedste time:',
    score_tip:'💡 Tilvælg målarter for at justere scoren til de valgte arters præferencer.',
    // Wind trend labels
    wind_rising_fast:'↑↑ Tiltagende kraftigt',
    wind_rising:'↑ Tiltagende',
    wind_falling_fast:'↓↓ Aftager kraftigt',
    wind_falling:'↓ Aftager',
    wind_stable:'→ Stabilt',
    // Pressure trend labels
    press_rising_fast:'Stigende kraftigt ↑↑',
    press_rising:'Svagt stigende ↑',
    press_stable:'Stabilt →',
    press_falling:'Svagt faldende ↓',
    press_falling_fast:'Faldende kraftigt ↓↓',
    press_fish_rising_fast:'📈 Hurtigt stigende tryk — fiskene aktiveres kraftigt og jager aggressivt. Et af de bedste tidsvinduer til kystfiskeri.',
    press_fish_rising:'📈 Stigende tryk — fiskenes aktivitet tiltar. Forventede gode bid, særligt i starten af stigningen.',
    press_fish_stable:'➡️ Stabilt tryk — fiskene har tilpasset sig og holder til på kendte dybder. Fiskeri er forudsigeligt, men ingen ekstra aktivitetspeak.',
    press_fish_falling:'📉 Faldende tryk — fiskene mærker det og fodrer aktivt inden trykket rammer bunden. Fang dem nu, mens de stadig er oppe.',
    press_fish_falling_fast:'📉 Kraftigt faldende tryk — fiskene trækker sig til bunden. Forvent sværere fiskeri; de fleste arter holder lav profil.',
    // Tide labels
    tide_rising:'🌊 Stigende tidevand',
    tide_falling:'🌊 Faldende tidevand',
    // Conditions tab
    cond_temp:'Temperatur', cond_wind:'Vind', cond_gust:'Vindstød',
    cond_cloud:'Skydække', cond_precip:'Nedbørschance',
    cond_wave:'Bølgehøjde', cond_period:'Bølgeperiode', cond_swell:'Dønning',
    cond_tide:'Tidevand', cond_tide_from:'Tidevand fra',
    wave_forecast:'📈 Bølgeprognose',
    // Spot finder
    sf_lucky_badge:'🎲 Held og lykke', sf_nearby_badge:'📍 Find i nærheden',
    sf_when:'🗓 Hvornår vil du ud og fiske?',
    sf_date:'Dato', sf_time:'Tidspunkt', sf_radius:'Radius',
    sf_from_where:'Fra hvor?',
    sf_geo_ph:'By, sted eller postnummer...',
    sf_search_btn:'📍 Find fiskepladser',
    sf_search_lucky:"🎲 Find Danmarks bedste spots",
    sf_no_results:'Ingen pladser fundet i denne radius.',
    sf_results_nearby:'Fiskepladser inden for',
    sf_results_km:'km',
    sf_add_to_locs:'+ Tilføj til mine lokationer',
    sf_goto_dash:'Gå til dashboard →',
    sf_use_location:'📍 Brug min placering',
    sf_searching:'Søger...',
    sf_dist:'km væk',
    sf_no_windows:'Ingen tidsvinduer',
    // Lure colors
    lure_silver:'Sølv', lure_pearl:'Perlemorshvid', lure_gold:'Guld',
    lure_chartreuse:'Chartreuse', lure_orange:'Orange', lure_red:'Rød',
    lure_firetiger:'Firetiger', lure_uvwhite:'UV-hvid', lure_green:'Grøn',
    lure_black:'Sort', lure_pink:'Pink',
    lure_reason_silver:'Klart vand + sol — naturlig blink',
    lure_reason_pearl:'Klart vand + sol — subtilt blinkende',
    lure_reason_gold:'Delvist overskyet — varm flash',
    lure_reason_chartreuse:'Overskyet / diffust lys — høj synlighed',
    lure_reason_orange:'Grumset vand / stærk vind — kontrastfarve',
    lure_reason_red:'Mørkt / grumset vand — maks kontrast',
    lure_reason_firetiger:'Høje bølger / silt — voldsom kontrast',
    lure_reason_uvwhite:'Lavt lys / morgen-aften — lyser op',
    lure_reason_green:'Grumset ferskvand — mimetisk',
    lure_reason_black:'Meget grumset / nat — silhuet-kontrast',
    lure_reason_pink:'Klart saltvandsforhold — havørred-favorit',
    lure_tip_murky:'Grumset vand: brug store, kraftige farver og langsommere bevægelse',
    lure_tip_lowlight:'Lavt lys: UV-hvid og chartreuse reflekterer diffust lys bedst',
    lure_tip_clear:'Klart stille vand: naturlige subtile farver — fiskene er sky',
    lure_tip_overcast:'Overskyet: mellemstærke attractor-farver virker godt i diffust lys',
    // Species tackle tips
    tip_hornfisk:'🐟 Hornfisk: brug silketråd eller små tripler på en dropper-line efter blinket — hornfisken hugger short',
    tip_gedde:'🐊 Gedde: brug stålfortom — geddens tænder skærer monofilament over',
    tip_sandart:'🐊 Sandart: langsom bundjigging 0.5–1.5 m over bunden — kræver tålmodighed',
    tip_aborre:'🐡 Aborre: drop-shot eller micro-jig 3–8 g — reagerer godt på langsom animation',
    tip_torsk:'🐡 Torsk: tung pilker 40–150 g afhængig af dybde og strøm — bund-rig med orm virker også',
    tip_havørred:'🐟 Havørred: blink, wobler eller flue langs bræmmer og stenrev — tidlig morgen bedst',
    tip_laks:'🐟 Laks: brug kraftig fortom (20–30 lb) og store wobler/spinners — fisk i strømmende vand',
    tip_al:'🐍 Ål: orm eller død agnfisk på bunden nat-fiskeri — fisk stille med slap linje',
    tip_makrel:'🐟 Makrel: sølv-sluk eller feathered jig i hurtig bevægelse — find stimerne visuelt',
    tip_fjaesing:'☠️ Fjæsing: vadefisk — ALTID vandsko/vadesko. Stikket er smertefuldt, nedsænk i varmt vand (45°C)',
    // Moon phases (from solunar.js)
    moon_new:'Nymåne', moon_waxing_crescent:'Tiltagende halvmåne',
    moon_first_quarter:'Første kvarter', moon_waxing_gibbous:'Tiltagende',
    moon_full:'Fuldmåne', moon_waning_gibbous:'Aftagende',
    moon_last_quarter:'Sidste kvarter', moon_waning_crescent:'Aftagende halvmåne',
    // Solunar periods
    solunar_major:'🌕 Majortid', solunar_minor:'🌙 Minortid',
    solunar_golden:'Gode fisketider:', solunar_none:'Ingen solunar periode i dette vindue',
    // Week sparkline
    best_day_week:'Bedste dag:', week_overview:'Ugeoversigt',
    // Water temperature
    water_temp:'Vandtemp.',
    // Conditions tab labels
    cond_beaufort:'Beaufort', cond_wind_trend:'Vindtrend',
    // Favourite spots
    fav_add:'Tilføj til favoritter', fav_remove:'Fjern fra favoritter',
    // Spot notes
    note_placeholder:'Tilføj note til dette sted…',
    note_label:'📝 Note', note_save:'Gem', note_saved:'✓ Gemt',
    // Stale data
    stale_banner:'Data fra', stale_banner2:'— kan være forældet.',
    stale_update:'Opdater nu',
    // Condition delta
    vs_yesterday:'vs. i går',
    // Wind relative to shore
    wind_onshore:'Pålandsvind', wind_offshore:'Aflandsvind',
    wind_cross_onshore:'Tværvind (ind)', wind_cross_offshore:'Tværvind (ud)',
    wind_shore_label:'Kystretning:',
    // Tide arrows on window cards
    tide_up:'↑ Stigende', tide_down:'↓ Faldende',
    // Min size / bag limit on species cards
    sp_min_size:'Min.', sp_bag_limit:'Dagskvoter:', sp_cr:'♻️ C&R anbefalet',
    // Pressure graph
    pressure_graph:'Lufttryk — 48 timer', pressure_hpa:'hPa',
    // Share
    share_btn:'🔗 Del', share_copied:'✓ Kopieret!', share_window:'Delt fiskevindue',
    share_add_loc:'+ Tilføj lokation', share_view_dash:'Gå til dashboard →',
    share_intro:'En anden FishCast-bruger har delt dette vindue med dig:',
    // Notifications
    notif_enable:'🔔 Påmindelser', notif_enabled:'🔔 Aktiv',
    notif_denied:'Notifikationer blokeret', notif_scheduled:'Påmindelser planlagt',
    notif_title:'🎣 FishCast — Godt vindue snart!',
    notif_none:'Ingen kommende vinduer at minde om',
    // Quick reset
    reset_data_btn:'🗑 Ryd vejrdata', reset_data_confirm:'Ryd alle gemte vejrdata? Lokationer og indstillinger beholdes.',
    reset_data_ok:'✓ Data ryddet',
  },
  en: {
    // General
    back:'← Back', next:'Next →', skip:'Skip →', close:'Close',
    add:'+ Add', added:'✓ Added', save:'Save', cancel:'Cancel',
    reset_btn:'🔄 Reset everything',
    reset_confirm:'Reset all — locations, time windows and target species will be deleted. Are you sure?',
    show_on_map:'Show on map 🗺', rename:'Rename',
    update_all:'⟳ Update all data', data_ok:'✓ Data',
    loading:'Loading…', error:'Error', details:'Details',
    // Days
    day0:'Sun',day1:'Mon',day2:'Tue',day3:'Wed',day4:'Thu',day5:'Fri',day6:'Sat',
    // Months
    month0:'Jan',month1:'Feb',month2:'Mar',month3:'Apr',month4:'May',month5:'Jun',
    month6:'Jul',month7:'Aug',month8:'Sep',month9:'Oct',month10:'Nov',month11:'Dec',
    // Welcome
    welcome_tagline:'Your personal fishing assistant.',
    welcome_sub:'Set your locations and time slots — we find the best window.',
    welcome_setup:'Set up my fishing spots →',
    welcome_continue:'Continue to dashboard',
    welcome_or:'or',
    welcome_shortcut:'Find fishing spots fast — no setup needed',
    welcome_lucky_title:'Lucky Cast',
    welcome_lucky_sub:"Find Denmark's best hotspot for a specific species",
    welcome_nearby_title:'Find Nearby',
    welcome_nearby_sub:'Search fishing spots within a given distance from you',
    attribution:'Weather: Open-Meteo · Tides + Lightning: DMI Open Data · Regulations: lfst.dk',
    // Availability
    avail_title:'When can you fish?',
    avail_sub:'Set your available time windows',
    avail_window:'Time Window',
    avail_add:'+ Add time window',
    avail_notice:'ℹ️ Add at least one time window to continue.',
    time_from:'From', time_to:'To',
    method_label:'Fishing method', method_pick:'Select one or more',
    method_required:'At least one method must be selected',
    method_shore:'Shore', method_waders:'Waders', method_boat:'From boat',
    fm_shore_hint:'Shore fishing / rod fishing from land',
    fm_waders_hint:'Wading — bottom type and undercurrent weighted',
    fm_boat_hint:'Boat trip — wave height and wind weighted harder',
    next_species:'Next: Target species →',
    next_choose_art:'Next: Choose species →',
    next_choose_start:'Next: Choose start location →',
    edit_time:'Edit →',
    // Water type
    wt_title:'What type of fishing water?',
    wt_sub:'Choose the water types you primarily fish in',
    wt_fact_hd:'Did you know?',
    wt_fact_body:"Most of Denmark's coast is <em>brackish</em> — not true saltwater. Kattegat, Øresund, the Danish straits and the Baltic Sea are all mixtures of salt and freshwater. Only the North Sea (Jutland's west coast) is true ocean. This means freshwater fish like pike and perch can live in many Danish harbours and fjords.",
    wt_most_dk:'Most common in DK',
    wt_fresh_label:'Freshwater', wt_fresh_sub:'Lakes, rivers and streams',
    wt_brackish_label:'Brackish', wt_brackish_sub:'Fjords, straits, Baltic Sea',
    wt_salt_label:'Saltwater', wt_salt_sub:'North Sea (west coast)',
    wt_both_label:'All water', wt_both_sub:'All water types',
    wt_salt_hint:'North Sea / true saltwater (~30–35 ppt)',
    wt_brackish_hint:'Kattegat, Øresund, Straits, Baltic Sea (~5–25 ppt). Mix of salt & freshwater species.',
    wt_fresh_hint:'Lakes, rivers and streams (~0 ppt)',
    wt_both_hint:'Varying water type — see spot description',
    wt_salt_label_full:'🌊 Saltwater',
    wt_brackish_label_full:'🌿 Brackish',
    wt_fresh_label_full:'💧 Freshwater',
    wt_both_label_full:'🗺 Mixed',
    wt_override:'Click to override water type',
    wt_override_warn:'⚠️ Overriding official data',
    // Locations
    loc_title:'Your fishing locations',
    loc_sub:'Search, browse official spots, or click directly on the map',
    loc_search_tab:'Search & Browse', loc_map_tab:'Map',
    loc_search_ph:'E.g. Køge, Esbjerg, Silkeborg...',
    loc_popular:'⭐ Popular fishing spots', loc_nearby_hd:'📍 Fishing spots nearby',
    loc_db_count:'spots in database',
    loc_empty:'No locations added yet',
    loc_official:'🎣 Official fishing spot', loc_custom:'📌 Custom spot',
    loc_brackish_note:'🌿 Brackish — both salt & freshwater species possible ℹ️',
    loc_in_season:'No active species this month',
    // Species
    sp_title:'Which species are you targeting?',
    sp_sub:'Choose your target species — the score adapts to their preferences',
    sp_show:'Show fishing conditions →',
    sp_lucky_btn:'🎲 Find best hotspot',
    sp_high_season:'⭐ Peak season now',
    sp_in_season:'✅ In season now', sp_restricted:'⚠️ With restrictions', sp_closed:'🚫 Closed season',
    sp_banned_label:'Catch banned', sp_restricted_label:'Restrictions',
    sp_handle:'Use pliers when handling',
    sp_regs_note:'⚠️ Regulations are advisory. Always verify at',
    // Dashboard
    dash_best:'🏆 Best window',
    dash_targets:'🎯 Target species:',
    dash_no_windows:'No time windows found. Add availability in the setup.',
    dash_no_forecast:'No weather data — press Update',
    tab_windows:'📅 Time windows', tab_seasons:'🐟 Fishing seasons', tab_conditions:'🌤 Weather & Waves',
    best_hour:'Best hour:',
    lure_label:'🎨 Lure:',
    your_locs:'📍 Your locations',
    moon_title:'🌙 Moon phase today',
    lightning_title:'⚡ Lightning status',
    no_lightning:'No lightning detected',
    update_lightning:'⟳ Update lightning',
    lightning_src:'Source: DMI · Last 45 min · Danish lightning only',
    lightning_checked:'Checked',
    explanation:'ℹ️ Explanation',
    sunrise:'Sunrise', sunset:'Sunset',
    moonrise:'Moonrise', moonset:'Moonset', culmination:'Culmination',
    moon_phase_today:'Phase:',
    moon_tip_new:'🌑 New moon — tides are at their strongest (spring tide). Fish are highly active; the best solunar periods align with sunrise and sunset.',
    moon_tip_full:'🌕 Full moon — peak solunar effect. Spring tides create strong currents and active fish. Night fishing can be exceptional.',
    moon_tip_quarter:'🌓 Quarter moon — neap tide with weaker currents. Fish are less active than at new/full moon, but solar periods still produce bites.',
    moon_tip_gibbous:'🌔 Gibbous moon — approaching peak. Activity is building as the lunar cycle nears its strongest point — fishing improves day by day.',
    no_windows_empty:'No time windows. Check your availability.',
    no_locs_empty:'No locations.',
    data_missing:'No weather data',
    load_data_btn:'Fetch weather', load_data_for:'Fetch data for', load_data_missing:'locations missing weather data',
    // Hardcoded strings
    locs_ready:'locations ready', locs_failed:'failed',
    invalid_window:'Invalid time window',
    no_official_spots:'No official fishing spots within 40 km',
    wt_salt_opt:'🌊 Saltwater (~33 ppt)', wt_brackish_opt:'🌿 Brackish (fjords, straits, Baltic)', wt_fresh_opt:'💧 Freshwater (lakes, rivers)',
    lightning_strikes_near:'strikes within',
    sf_no_spots_found:'No spots found', sf_no_spots_db:'in the database', sf_no_spots_radius:'within',
    sf_try_broader:'Try a broader search, or add your location manually via 📍 Locations → Map.',
    sf_score_hint:'Spot score based on species, season and habitat — weather data loads after you add the spot',
    score_lightning_name:'Lightning safety', score_lightning_desc:'Active lightning within 10 km caps the score at 15 and shows a red warning. Carbon rods conduct lightning — never fish in a storm.',
    // Score modal factors
    fac_pressure_name:'Pressure trend', fac_pressure_desc:'Rising pressure → fish activate and hunt actively. Falling pressure → they retreat to the bottom. The single most important factor.',
    fac_solunar_name:'Solunar periods', fac_solunar_desc:'Lunar culmination (overhead/underfoot) gives the biggest activity periods. Major periods = +30 points, minor (rise/set) = +15.',
    fac_timeofday_name:'Time of day', fac_timeofday_desc:'Dawn (±1h sunrise) is best (+20). Dusk is second best (+15). Midday is penalized (−10). Night fishing is neutral.',
    fac_tide_name:'Tide', fac_tide_desc:'Saltwater only. A rising tide markedly activates coastal fish. Sourced from DMI\'s official tide data for the nearest station.',
    fac_wave_name:'Wave height', fac_wave_desc:'< 0.3m: ideal (+5). 0.6–1m: penalty (−6). > 1m: heavy penalty. Species like turbot prefer light wave action — adjusted by target species.',
    fac_wind_name:'Wind', fac_wind_desc:'Light wind (< 3 m/s) gives +7. Above 8 m/s gives −18. Increasing wind is penalized extra. Direction also matters (W/WNW = best).',
    fac_cloud_name:'Cloud cover', fac_cloud_desc:'Overcast (> 65%) gives +8 points. Fish are more active in diffuse light — harder to see and hunting more freely.',
    fac_precip_name:'Precipitation chance', fac_precip_desc:'> 65% precipitation chance is treated as thunderstorm risk and penalized hard (−20). Fishing with carbon rods near lightning is also discouraged.',
    fac_moon_name:'Moon phase', fac_moon_desc:'New and full moon give extra activity (+15). Quarter moon gives +5. Computed astronomically for the exact date and position.',
    fac_species_name:'Species preferences', fac_species_desc1:'Bonus for your selected target species:', fac_species_desc2:'The score increases when conditions match the species\' specific preferences.',
    fac_spot_name:'Spot relevance', fac_spot_desc:'Bonus if the fishing spot has your target species registered as active this month (from fishingindenmark.info). Official spot data.',
    score_modal_intro:'The score (0–100) combines all weather, astronomical and spot-specific factors into one easy-to-read recommendation.',
    score_modal_legend:'80+ = Excellent · 65–79 = Good · 45–64 = Average · below 45 = Poor.',
    score_breakdown_for:'📊 Actual point breakdown for:', score_total:'Total score', factor_explain:'Factor explanations',
    up_to:'up to', points:'points',
    score_modal_tip:'💡 Select target species in setup for even more precise recommendations.',
    understood:'Got it',
    // Misc UI
    species_step_notice:'ℹ️ Select no species for a general recommendation, or pick one or more for targeted scoring.',
    selected_label:'Selected:',
    no_species_selected:'None selected — searching all species',
    click_remove:'Click to remove',
    customize_open:'+ Customize ▼', customize_close:'Close ▲',
    no_active_nearby:'No active species nearby this month',
    estimate_based:'Estimate based on:', estimate_from:'Estimate from:',
    found_count:'found',
    best_hotspots:'🏆 Best hotspots',
    closed_active:'closed season active',
    // Solunar / astronomy labels
    moon_lbl_new:'New moon', moon_lbl_waxing:'Waxing', moon_lbl_quarter:'Quarter moon', moon_lbl_full:'Full moon', moon_lbl_waning:'Waning',
    sol_culm:'Lunar culmination', sol_under:'Lunar underfoot', sol_rise:'Moonrise', sol_set:'Moonset', sol_approach:'Approaching lunar period',
    tod_dawn:'Dawn (peak activity)', tod_dusk:'Dusk (good activity)', tod_night:'Night', tod_midday:'Midday (low activity)',
    // Score breakdown factors & tags
    bd_pressure:'Pressure', bd_pressure_hint:'The pressure trend affects fish activity levels',
    bd_solunar:'Solunar', bd_solunar_none:'No active solunar period', bd_solunar_hint:'The moon\'s position drives the fish activity cycle',
    sol_major_word:'major', sol_minor_word:'minor', sol_tag_hint:'period — fish are markedly more active',
    bd_timeofday:'Time of day', bd_timeofday_none:'No notable daytime activity', bd_timeofday_hint:'Time relative to sunrise/sunset',
    bd_cloud:'Cloud cover', cloud_word:'cloud cover', bd_cloud_hint:'Overcast (>65%) gives +8 — fish hunt more freely in diffuse light',
    tag_overcast:'☁ Overcast', cloud_tag_hint:'fish hunt more actively',
    bd_wind:'Wind', bd_wind_hint:'Light wind is ideal; strong wind makes fishing difficult',
    tag_wind_light:'💨 Light wind', wind_light_word:'Light wind', wind_ideal:'ideal conditions',
    tag_wind_strong:'💨 Strong wind', wind_strong_word:'Strong wind', wind_difficult:'difficult conditions',
    bd_precip:'Precipitation', precip_word:'precipitation chance', bd_precip_hint:'>70% = thunderstorm risk, heavy penalty',
    tag_thunder:'🌧 Thunderstorm risk', thunder_tag_hint:'thunderstorm risk — carbon rods attract lightning!',
    bd_windtrend:'Wind trend', windtrend_worse:'Rising wind gradually worsens conditions', windtrend_better:'Falling wind improves conditions',
    windtrend_tag_rising:'Wind increasing', windtrend_tag_falling:'Wind decreasing',
    windtrend_over3h:'m/s over 3 hours — conditions', windtrend_worsen:'worsening', windtrend_improve:'improving',
    bd_winddir:'Wind direction', wind_suffix:' wind', bd_winddir_hint:'W/WNW = best; NE/E = unfavourable (old fishing wisdom)',
    unfavourable:'unfavourable', winddir_tag_hint:'is traditionally considered unfavourable for fishing',
    bd_wave:'Wave height', wave_word:'waves', wave_height_word:'wave height',
    wave_danger:'Dangerous seas', wave_high:'High seas', wave_calm_lbl:'Flat calm',
    wave_danger_hint:'dangerous conditions, strongly discouraged', wave_high_hint:'difficult conditions',
    wave_care_hint:'light caution advised when wading', wave_calm_hint:'nearly flat calm, ideal for all methods',
    bd_method:'Fishing method', at_word:'at', bd_method_hint:'Extra weighting for the chosen fishing method',
    bd_tide:'Tide', tide_rising_word:'↑ Rising', tide_falling_word:'↓ Falling', tide_none:'No tide',
    bd_tide_hint:'A rising tide markedly activates coastal fish',
    tide_tag_rising:'Rising tide at', tide_tag_falling:'Falling tide at',
    tide_activates:'activates coastal fish', tide_moderate:'moderate activity',
    bd_moon:'Moon phase', bd_moon_hint:'New and full moon give extra activity',
    bd_lightning:'Lightning risk', thunder_risk:'Thunderstorm risk', bd_lightning_hint:'High precipitation chance = possible thunderstorm, extra penalty',
    bd_species_hint:'Conditions match your selected target species\' preferences',
    // Toasts / connectivity
    toast_fetch_failed:'Couldn\'t load weather data for', toast_retry:'Retry',
    toast_offline:'You\'re offline — weather data can\'t be loaded', toast_back_online:'Back online — refreshing weather…',
    toast_refreshing_stale:'Refreshing outdated weather data…',
    // Setup sharing
    setup_share_btn:'📤 Share my setup', setup_link_copied:'✓ Link copied — send it to a fishing buddy',
    setup_shared_title:'Shared setup', setup_shared_intro:'Another FishCast user shared their setup with you:',
    setup_import:'Import setup', setup_import_warn:'Replaces your current locations, target species and time slots.',
    setup_sum_locs:'locations', setup_sum_species:'target species', setup_sum_slots:'time slots',
    topbar_species:'🎯 Species', topbar_locations:'📍 Locations', topbar_times:'⏱ Time slots',
    save_back_dash:'Save and back to dashboard',
    // Score labels
    score_excellent:'Excellent', score_good:'Good', score_avg:'Average',
    score_below:'Below average', score_poor:'Poor',
    // Score info modal
    score_modal_title:'📊 Fishing index — explanation',
    score_modal_base:'Base value for all windows',
    score_breakdown_title:'Score breakdown (best hour):',
    score_tip:'💡 Select target species to adjust the score to their preferences.',
    // Wind trend labels
    wind_rising_fast:'↑↑ Increasing rapidly',
    wind_rising:'↑ Increasing',
    wind_falling_fast:'↓↓ Decreasing rapidly',
    wind_falling:'↓ Decreasing',
    wind_stable:'→ Stable',
    // Pressure trend labels
    press_rising_fast:'Rising rapidly ↑↑',
    press_rising:'Slightly rising ↑',
    press_stable:'Stable →',
    press_falling:'Slightly falling ↓',
    press_falling_fast:'Falling rapidly ↓↓',
    press_fish_rising_fast:'📈 Rapidly rising pressure — fish are feeding aggressively. One of the best windows for shore fishing.',
    press_fish_rising:'📈 Rising pressure — fish activity is building. Expect good bites, especially early in the rise.',
    press_fish_stable:'➡️ Stable pressure — fish have settled at their usual depths. Fishing is predictable but no extra activity peak expected.',
    press_fish_falling:'📉 Falling pressure — fish sense the drop and feed actively before it bottoms out. Get out while they\'re still up.',
    press_fish_falling_fast:'📉 Rapidly falling pressure — fish retreat to deeper water. Most species go quiet; expect a tough session.',
    // Tide labels
    tide_rising:'🌊 Rising tide',
    tide_falling:'🌊 Falling tide',
    // Conditions tab
    cond_temp:'Temperature', cond_wind:'Wind', cond_gust:'Gusts',
    cond_cloud:'Cloud cover', cond_precip:'Precip. chance',
    cond_wave:'Wave height', cond_period:'Wave period', cond_swell:'Swell',
    cond_tide:'Tide', cond_tide_from:'Tide station',
    wave_forecast:'📈 Wave forecast',
    // Spot finder
    sf_lucky_badge:'🎲 Lucky Cast', sf_nearby_badge:'📍 Find Nearby',
    sf_when:'🗓 When do you want to fish?',
    sf_date:'Date', sf_time:'Time', sf_radius:'Radius',
    sf_from_where:'From where?',
    sf_geo_ph:'Town, place or postcode...',
    sf_search_btn:'📍 Find fishing spots',
    sf_search_lucky:"🎲 Find Denmark's best spots",
    sf_no_results:'No spots found within this radius.',
    sf_results_nearby:'Fishing spots within',
    sf_results_km:'km',
    sf_add_to_locs:'+ Add to my locations',
    sf_goto_dash:'Go to dashboard →',
    sf_use_location:'📍 Use my location',
    sf_searching:'Searching...',
    sf_dist:'km away',
    sf_no_windows:'No time windows',
    // Lure colors
    lure_silver:'Silver', lure_pearl:'Pearl white', lure_gold:'Gold',
    lure_chartreuse:'Chartreuse', lure_orange:'Orange', lure_red:'Red',
    lure_firetiger:'Firetiger', lure_uvwhite:'UV white', lure_green:'Green',
    lure_black:'Black', lure_pink:'Pink',
    lure_reason_silver:'Clear water + sun — natural flash',
    lure_reason_pearl:'Clear water + sun — subtle shine',
    lure_reason_gold:'Partly cloudy — warm flash',
    lure_reason_chartreuse:'Overcast / diffuse light — high visibility',
    lure_reason_orange:'Murky water / strong wind — contrast colour',
    lure_reason_red:'Dark / murky water — max contrast',
    lure_reason_firetiger:'High waves / silt — extreme contrast',
    lure_reason_uvwhite:'Low light / dawn-dusk — glows up',
    lure_reason_green:'Murky freshwater — mimetic',
    lure_reason_black:'Very murky / night — silhouette contrast',
    lure_reason_pink:'Clear saltwater — sea trout favourite',
    lure_tip_murky:'Murky water: use large, bold colours and slower retrieves',
    lure_tip_lowlight:'Low light: UV white and chartreuse reflect diffuse light best',
    lure_tip_clear:'Clear calm water: natural subtle colours — fish are wary',
    lure_tip_overcast:'Overcast: medium-strength attractor colours work well in diffuse light',
    // Species tackle tips
    tip_hornfisk:'🐟 Garfish: use silk thread or small treble hooks on a dropper-line behind the lure — garfish strike short',
    tip_gedde:'🐊 Pike: use a wire leader — pike teeth cut through monofilament',
    tip_sandart:'🐊 Zander: slow bottom jigging 0.5–1.5 m above the bottom — requires patience',
    tip_aborre:'🐡 Perch: drop-shot or micro-jig 3–8 g — responds well to slow animation',
    tip_torsk:'🐡 Cod: heavy pirk 40–150 g depending on depth and current — bottom rig with worm also works',
    tip_havørred:'🐟 Sea trout: spinner, wobbler or fly along edges and rock reefs — early morning best',
    tip_laks:'🐟 Salmon: use strong leader (20–30 lb) and large wobblers/spinners — fish in running water',
    tip_al:'🐍 Eel: worm or dead baitfish on the bottom at night — fish still with slack line',
    tip_makrel:'🐟 Mackerel: silver lure or feathered jig retrieved fast — find the schools visually',
    tip_fjaesing:'☠️ Greater Weever: wading — ALWAYS wear water shoes. The sting is painful; submerge in hot water (45°C)',
    // Moon phases (from solunar.js)
    moon_new:'New Moon', moon_waxing_crescent:'Waxing Crescent',
    moon_first_quarter:'First Quarter', moon_waxing_gibbous:'Waxing Gibbous',
    moon_full:'Full Moon', moon_waning_gibbous:'Waning Gibbous',
    moon_last_quarter:'Last Quarter', moon_waning_crescent:'Waning Crescent',
    // Solunar periods
    solunar_major:'🌕 Major period', solunar_minor:'🌙 Minor period',
    solunar_golden:'Good fishing times:', solunar_none:'No solunar period in this window',
    // Week sparkline
    best_day_week:'Best day:', week_overview:'Week overview',
    // Water temperature
    water_temp:'Water temp.',
    // Conditions tab labels
    cond_beaufort:'Beaufort', cond_wind_trend:'Wind trend',
    // Favourite spots
    fav_add:'Add to favourites', fav_remove:'Remove from favourites',
    // Spot notes
    note_placeholder:'Add a note for this spot…',
    note_label:'📝 Note', note_save:'Save', note_saved:'✓ Saved',
    // Stale data
    stale_banner:'Data from', stale_banner2:'— may be outdated.',
    stale_update:'Update now',
    // Condition delta
    vs_yesterday:'vs. yesterday',
    // Wind relative to shore
    wind_onshore:'Onshore wind', wind_offshore:'Offshore wind',
    wind_cross_onshore:'Crosswind (in)', wind_cross_offshore:'Crosswind (out)',
    wind_shore_label:'Shore direction:',
    // Tide arrows on window cards
    tide_up:'↑ Rising', tide_down:'↓ Falling',
    // Min size / bag limit on species cards
    sp_min_size:'Min.', sp_bag_limit:'Bag limit:', sp_cr:'♻️ C&R recommended',
    // Pressure graph
    pressure_graph:'Air pressure — 48 hours', pressure_hpa:'hPa',
    // Share
    share_btn:'🔗 Share', share_copied:'✓ Copied!', share_window:'Shared fishing window',
    share_add_loc:'+ Add location', share_view_dash:'Go to dashboard →',
    share_intro:'Another FishCast user shared this window with you:',
    // Notifications
    notif_enable:'🔔 Reminders', notif_enabled:'🔔 Active',
    notif_denied:'Notifications blocked', notif_scheduled:'Reminders scheduled',
    notif_title:'🎣 FishCast — Great window soon!',
    notif_none:'No upcoming windows to remind about',
    // Quick reset
    reset_data_btn:'🗑 Clear weather data', reset_data_confirm:'Clear all cached weather data? Locations and settings are kept.',
    reset_data_ok:'✓ Data cleared',
  }
};
