/**
 * FishCast - i18n string table (da/en)
 * Loaded before app.js; consumed by the global t() helper there.
 */

// ═══════════════════════════════════════════
//  INTERNATIONALISATION (i18n)
// ═══════════════════════════════════════════
export const STRINGS: Record<string, Record<string, string>> = {
  da: {
    // General
    back:'← Tilbage', next:'Næste →', skip:'Spring over →', close:'Luk',
    add:'+ Tilføj', added:'✓ Tilføjet', save:'Gem', cancel:'Annuller',
    reset_btn:'🔄 Start forfra — nulstil alt',
    reset_confirm:'Nulstil alt — lokationer, tidsvinduer og målarter slettes. Er du sikker?',
    show_on_map:'Vis på kort 🗺', rename:'Omdøb',
    update_all:'⟳ Opdater alle data', data_ok:'✓ Data',
    updated_prefix:'Opdateret', time_just_now:'lige nu', time_min_ago:'min. siden', time_hr_ago:'t. siden',
    cal_title:'Fisketur', cal_score:'Score', cal_add:'Føj til kalender',
    dlg_confirm:'Bekræft', dlg_cancel:'Annullér',
    topbar_log:'📒 Fangstlog', log_title:'Fangstlog',
    log_add:'Registrér fangst', log_date:'Dato', log_species:'Art', log_species_other:'Anden / ukendt',
    log_location:'Lokation', log_location_ph:'Hvor fangede du den?',
    log_length:'Længde (cm)', log_weight:'Vægt (kg)', log_notes:'Noter', log_notes_ph:'Agn, vejr, metode…',
    log_optional:'· valgfri', log_not_measured:'ikke målt', log_count:'Antal',
    log_save:'Gem fangst', log_empty_title:'Ingen fangster endnu', log_empty_sub:'Registrér din første fangst ovenfor.',
    log_total:'fangster', log_remove:'Slet fangst', log_remove_confirm:'Slet denne fangst?',
    log_edit:'Redigér', log_edit_h:'Redigér fangst', log_update:'Opdater fangst', log_cancel:'Annullér',
    log_stat_catches:'Fangster', log_stat_longest:'Længste', log_stat_heaviest:'Tungeste', log_stat_top:'Hyppigste art',
    log_outcome:'Beholdt eller genudsat?', log_kept:'Beholdt', log_released:'Genudsat', log_stat_released:'Genudsat',
    log_time:'Tidspunkt', log_score_btn:'⚡ Beregn bid-score', log_score_label:'Bid-score', log_scoring:'Beregner…', log_score_na:'Ingen data for dette tidspunkt',
    guard_undersize:'Under mindstemål: {len} cm < {min} cm', guard_closed:'Muligvis i fredningstid på denne dato — tjek reglerne',
    insight_title:'Modeltjek', insight_run:'Analysér fangster', insight_avg:'Gns. bid-score da du fangede',
    insight_sub:'Sammenligner modellens score med hvornår du faktisk fangede fisk. {n} fangster kan analyseres (kræver tidspunkt + en gemt lokation).',
    insight_dist:'Fordeling af bid-scores ved fangst',
    insight_thin:'For få fangster til at sige noget meningsfuldt endnu — registrér flere med tidspunkt og lokation.',
    insight_strong:'De fleste af dine fangster skete i gode tidsvinduer — modellen ser ud til at passe på dit fiskeri.',
    insight_mixed:'Blandet billede: du fanger både i gode og mindre gode vinduer. Modellen er en indikation, ikke en garanti.',
    insight_weak:'Dine fangster sker mest i lavt scorede vinduer — modellen passer ikke godt til dit fiskeri (eller du fisker mest på svære tidspunkter).',
    loading:'Henter…', error:'Fejl', details:'Detaljer',
    // Days
    day0:'Søn',day1:'Man',day2:'Tir',day3:'Ons',day4:'Tor',day5:'Fre',day6:'Lør',
    // Months
    month0:'Jan',month1:'Feb',month2:'Mar',month3:'Apr',month4:'Maj',month5:'Jun',
    month6:'Jul',month7:'Aug',month8:'Sep',month9:'Okt',month10:'Nov',month11:'Dec',
    // Welcome
    welcome_tagline:'Din personlige fiskeassistent.',
    welcome_sub:'Angiv dine lokationer og tidspunkter — vi finder det bedste vindue.',
    welcome_setup:'Opsæt mine fiskepladser →',
    welcome_continue:'Fortsæt til dashboard',
    welcome_or:'eller',
    welcome_shortcut:'Find fiskesteder hurtigt — ingen opsætning nødvendig',
    welcome_lucky_title:'Held og lykke',
    welcome_lucky_sub:'Find Danmarks bedste hotspot for en bestemt art',
    welcome_nearby_title:'Find i nærheden',
    welcome_nearby_sub:'Søg fiskepladser inden for en given afstand fra dig',
    attribution:'Vejrdata: Open-Meteo · Tidevand + Lyn: DMI Open Data · Regler: lfst.dk',
    // Availability
    avail_title:'Hvornår kan du fiske?',
    avail_sub:'Angiv dine tilgængelige tidsvinduer',
    avail_window:'Tidsvindue',
    avail_add:'+ Tilføj tidsvindue',
    avail_notice:'ℹ️ Tilføj mindst ét tidsvindue for at fortsætte.',
    avail_time_warn:'Sluttid skal være efter starttid', avail_days_warn:'Vælg mindst én dag',
    avail_fix_before_next:'Ret tidsvinduet ovenfor før du går videre — et vindue der slutter før det starter kan ikke beregnes.',
    time_from:'Fra', time_to:'Til',
    method_label:'Fiskemetode', method_pick:'Vælg en eller flere',
    method_required:'Mindst én metode skal være valgt',
    method_shore:'Fra kyst', method_waders:'Waders', method_boat:'Fra båd',
    fm_shore_hint:'Kystfiskeri / stangfiskeri fra land',
    fm_waders_hint:'Vadefiskeri — bundtype og underdrift vægtes',
    fm_boat_hint:'Bådtur — bølgehøjde og vind vægtes hårdere',
    next_species:'Næste: Målarter →',
    next_choose_art:'Næste: Vælg art →',
    next_choose_start:'Næste: Vælg startsted →',
    edit_time:'Rediger →',
    // Water type
    wt_title:'Hvilken type fiskevand?',
    wt_sub:'Vælg de vandtyper du primært fisker i',
    wt_fact_hd:'Vidste du?',
    wt_fact_body:'Det meste af Danmarks kyst er <em>brakvand</em> — ikke ægte saltvand. Kattegat, Øresund, de danske bælter og Østersøen er alle blandinger af salt- og ferskvand. Kun Nordsøen (Jyllands vestkyst) er rigtigt hav. Det betyder at ferskvandsfisk som gedde og aborre kan leve i mange danske havne og fjorde.',
    wt_most_dk:'Mest i DK',
    wt_fresh_label:'Ferskvand', wt_fresh_sub:'Søer, åer og vandløb',
    wt_brackish_label:'Brakvand', wt_brackish_sub:'Fjorde, bælter, Østersøen',
    wt_salt_label:'Saltvand', wt_salt_sub:'Nordsøen (vestkysten)',
    wt_both_label:'Alt vand', wt_both_sub:'Alle vandtyper',
    wt_salt_hint:'Nordsøen / ægte saltvand (~30–35 ppt)',
    wt_brackish_hint:'Kattegat, Øresund, Bælterne, Østersøen (~5–25 ppt). Blanding af salt- og ferskvandsarter.',
    wt_fresh_hint:'Søer, åer og vandløb (~0 ppt)',
    wt_both_hint:'Varierende vandtype — se stedets beskrivelse',
    wt_salt_label_full:'🌊 Saltvand',
    wt_brackish_label_full:'🌿 Brakvand',
    wt_fresh_label_full:'💧 Ferskvand',
    wt_both_label_full:'🗺 Blandet',
    wt_override:'Klik for at overstyre vandtype',
    wt_override_warn:'⚠️ Overstyrende officielle data',
    // Locations
    loc_title:'Dine fiskelokationer',
    loc_sub:'Søg, browse officielle pladser, eller klik direkte på kortet',
    loc_search_tab:'Søg & Browse', loc_map_tab:'Kort',
    loc_search_ph:'F.eks. Køge, Esbjerg, Silkeborg...',
    loc_popular:'⭐ Populære fiskepladser', loc_nearby_hd:'📍 Fiskepladser i nærheden',
    loc_db_count:'pladser i database',
    loc_empty:'Ingen lokationer tilføjet endnu',
    loc_official:'🎣 Officielt fiskested', loc_custom:'📌 Brugerdefineret spot',
    loc_brackish_note:'🌿 Brakvand — salt- og ferskvandsarter mulige ℹ️',
    loc_in_season:'Ingen aktive arter denne måned',
    // Species
    sp_title:'Hvilke arter fisker du efter?',
    sp_sub:'Vælg dine målarter — scoren tilpasses de valgte arters præferencer',
    sp_show:'Vis fiskeforhold →',
    sp_lucky_btn:'🎲 Find bedste hotspot',
    sp_high_season:'⭐ Høj sæson nu',
    sp_in_season:'✅ I sæson nu', sp_restricted:'⚠️ Med begrænsninger', sp_closed:'🚫 Lukket sæson',
    sp_banned_label:'Fangst forbudt', sp_restricted_label:'Begrænsninger',
    sp_handle:'Brug tang ved håndtering',
    sp_regs_note:'⚠️ Regler er vejledende. Verificér altid på',
    // Dashboard
    dash_best:'🏆 Bedste vindue',
    dash_targets:'🎯 Målarter:',
    dash_no_windows:'Ingen tidsvinduer fundet. Tilføj en tilgængelighed i opsætningen.',
    dash_no_forecast:'Ingen vejrdata — tryk Opdater',
    tab_windows:'📅 Tidsvinduer', tab_seasons:'🐟 Fiskesæsoner', tab_conditions:'🌤 Vejr & Bølger',
    best_hour:'Bedste time:',
    lure_label:'🎨 Agn:',
    your_locs:'📍 Dine lokationer',
    moon_title:'🌙 Månefase i dag',
    lightning_title:'⚡ Lyn-status',
    no_lightning:'Ingen lyn registreret',
    update_lightning:'⟳ Opdater lyn',
    lightning_src:'Kilde: DMI · Sidst 45 min · Kun lyn i Danmark',
    lightning_checked:'Tjekket',
    explanation:'ℹ️ Forklaring',
    sunrise:'Solopgang', sunset:'Solnedgang',
    moonrise:'Måneopgang', moonset:'Månenedgang', culmination:'Kulminering',
    moon_phase_today:'Fase:',
    moon_tip_new:'🌑 Nymåne — vandstanden ændrer sig mest (springflod). Fiskene er ekstra aktive; de bedste majortider falder tæt på solop- og nedgang.',
    moon_tip_full:'🌕 Fuldmåne — stærkeste solunareffekt. Springflod giver kraftige strømme og aktive fisk. Især natfiskeri kan være fremragende.',
    moon_tip_quarter:'🌓 Kvartmåne — neapflod med svagere strøm. Fiskene er mindre aktive end ved ny- og fuldmåne, men solaktive perioder virker stadig.',
    moon_tip_gibbous:'🌔 Gibbøs måne — næsten fuld/ny. Aktiviteten stiger — fiskenes appetit tiltar efterhånden som månecyklussen nærmer sig sit højdepunkt.',
    no_windows_empty:'Ingen tidsvinduer. Tjek din tilgængelighed.',
    no_locs_empty:'Ingen lokationer.',
    data_missing:'Ingen vejrdata',
    load_data_btn:'Hent vejrdata', load_data_for:'Hent data til', load_data_missing:'lokationer mangler vejrdata',
    // Hardcoded strings
    locs_ready:'lokationer klar', locs_failed:'fejlede',
    invalid_window:'Ugyldigt tidsvindue',
    no_official_spots:'Ingen officielle fiskesteder inden for 40 km',
    wt_salt_opt:'🌊 Saltvand (~33 ppt)', wt_brackish_opt:'🌿 Brakvand (fjorde, bælter, Østersøen)', wt_fresh_opt:'💧 Ferskvand (søer, åer)',
    lightning_strikes_near:'lynnedslag i',
    sf_no_spots_found:'Ingen pladser fundet', sf_no_spots_db:'i databasen', sf_no_spots_radius:'inden for',
    sf_try_broader:'Prøv en bredere søgning, eller tilføj din lokation manuelt via 📍 Lokationer → Kort.',
    sf_score_hint:'Pladsscore baseret på art, sæson og habitat — vejrdata hentes efter du tilføjer stedet',
    score_lightning_name:'Lynsikkerhed', score_lightning_desc:'Aktive lynslag inden for 10 km sætter scoren til maks 15 og viser rød advarsel. Kulstofstænger er lynledere — gå aldrig ud.',
    // Score modal factors
    fac_pressure_name:'Lufttryk trend', fac_pressure_desc:'Stigende tryk → fiskene aktiveres og jager aktivt. Faldende tryk → de trækker sig mod bunden. Den vigtigste enkeltfaktor.',
    fac_solunar_name:'Solunare perioder', fac_solunar_desc:'Månens kulminering (overhead/underfoot) giver de største aktivitetsperioder. Major perioder = +30 point, minor (op/ned) = +15.',
    fac_timeofday_name:'Tidspunkt på dagen', fac_timeofday_desc:'Daggry (±1t solopgang) er bedst (+20). Skumring er næstbedst (+15). Middag giver straf (−10). Nattefiskeri er neutralt.',
    fac_tide_name:'Tidevand', fac_tide_desc:'Kun ved saltvand. Stigende tidevand aktiverer kystfisk markant. Hentes fra DMIs officielle tidevandsdata for nærmeste station.',
    fac_wave_name:'Bølgehøjde', fac_wave_desc:'< 0.3m: ideelt (+5). 0.6–1m: straf (−6). > 1m: stor straf. Arter som Pighvar foretrækker let bølgegang — tilpasses af artsmål.',
    fac_wind_name:'Vind', fac_wind_desc:'Svag vind (< 3 m/s) giver +7. Over 8 m/s giver −18. Stigende vind straffes ekstra. Vindretning påvirker også (V/VNV = bedst).',
    fac_cloud_name:'Skydække', fac_cloud_desc:'Overskyet (> 65%) giver +8 point. Fisk er mere aktive i diffust lys — de er sværere at se og jager mere frit.',
    fac_precip_name:'Nedbørschance', fac_precip_desc:'> 65% nedbørschance tolkes som tordenvejrsrisiko og straffes hårdt (−20). Desuden frarådes fiskeri med kulstofstænger ved lyn.',
    fac_moon_name:'Månefase', fac_moon_desc:'Ny- og fuldmåne giver ekstra aktivitet (+15). Halvmåne giver +5. Beregnes astronomisk for præcis dato og position.',
    fac_species_name:'Artspræferencer', fac_species_desc1:'Bonus for dine valgte målarter:', fac_species_desc2:'Scoren øges når betingelserne matcher artens specifikke præferencer.',
    fac_spot_name:'Spotrelevans', fac_spot_desc:'Bonus hvis fiskepladsen har dine målarter registreret som aktive denne måned (fra fishingindenmark.info). Officielle stedsdata.',
    score_modal_intro:'Scoren (0–100) samler alle vejr-, astronomiske og stedsspecifikke faktorer til én letlæselig anbefaling.',
    score_modal_legend:'80+ = Fremragende · 65–79 = Godt · 45–64 = Middel · under 45 = Dårligt.',
    score_breakdown_for:'📊 Faktisk pointfordeling for:', score_total:'Samlet score', factor_explain:'Faktorforklaring',
    up_to:'op til', points:'point',
    score_modal_tip:'💡 Vælg målarter i opsætningen for endnu mere præcise anbefalinger.',
    understood:'Forstået',
    // Misc UI
    species_step_notice:'ℹ️ Vælg ingen arter for en generel anbefaling, eller vælg en eller flere for målrettet scoring.',
    selected_label:'Valgte:',
    no_species_selected:'Ingen valgt — søger alle arter',
    click_remove:'Klik for at fjerne',
    customize_open:'+ Tilpas ▼', customize_close:'Luk ▲',
    no_active_nearby:'Ingen aktive arter denne måned nærved',
    estimate_based:'Estimat baseret på:', estimate_from:'Estimat fra:',
    found_count:'fundet',
    best_hotspots:'🏆 Bedste hotspots',
    closed_active:'fredning aktiv',
    // Solunar / astronomy labels
    moon_lbl_new:'Nymåne', moon_lbl_waxing:'Tiltagende', moon_lbl_quarter:'Halvmåne', moon_lbl_full:'Fuldmåne', moon_lbl_waning:'Aftagende',
    sol_culm:'Månens kulminering', sol_under:'Månens lavpunkt', sol_rise:'Måneopgang', sol_set:'Månenedgang', sol_approach:'Nærmer sig månens periode',
    tod_dawn:'Daggry (topaktivitet)', tod_dusk:'Skumring (god aktivitet)', tod_night:'Nat', tod_midday:'Midt på dagen (lav aktivitet)',
    // Score breakdown factors & tags
    bd_base:'Basis', dash_window_avg:'Vinduets gennemsnit',
    bd_window_note:'Pointene er gennemsnit af forholdene henover tidsvinduet.',
    dash_trend:'7-dages prognose for dette tidsvindue',
    dash_view:'Visning', dash_simple:'Simpel', dash_full:'Fuld',
    dash_horizon:'Hvor langt frem skal vi kigge?', dash_h_today:'I dag', dash_h_days:'dage',
    tab_map:'🗺 Kort', map_no_score:'Ingen score i perioden',
    maptab_hint:'Bedste score pr. plads i den valgte periode. Nærliggende pladser deler ofte vejr, så forskelle skyldes typisk vandtype, bund og læ.',
    maptab_spread:'Spredning', maptab_spread_low:'(pladserne ligner hinanden)', maptab_spread_high:'(pladserne skiller sig ud)',
    maptab_compare:'Sammenlign med officielle pladser i nærheden',
    maptab_compare_loading:'Henter vejr og scorer pladser…',
    maptab_compare_none:'Ingen officielle pladser inden for 30 km',
    maptab_km_away:'km væk', maptab_better:'scorer højere end dine egne pladser i denne periode',
    dash_none_in_horizon:'Ingen tidsvinduer i den valgte periode.', dash_show_week:'Vis hele ugen',
    dash_fetching:'Henter nye vejrdata…',
    conf_days:'dage frem', conf_med:'middel prognosesikkerhed', conf_low:'lav prognosesikkerhed',
    conf_hint:'Prognosen bliver mindre sikker længere ude i fremtiden',
    dash_top_pick:'Ugens bedste', dash_showing_day:'Viser', dash_show_all_days:'Vis alle dage',
    dash_showing:'Viser', dash_of:'af', dash_show_more:'Vis flere', dash_show_all:'Vis alle',
    map_add_cta:'Tryk et vilkårligt sted på kortet for at tilføje en fiskeplads',
    relevance_active:'målart(er) aktive her',
    loc_open_map:'🗺 Vælg egne pladser på kortet', loc_open_map_sub:'Tryk på kortet for at tilføje et hvilket som helst sted',
    bd_pressure:'Lufttryk', bd_pressure_hint:'Lufttryk trend påvirker fiskenes aktivitetsniveau',
    bd_solunar:'Solunar', bd_solunar_none:'Ingen aktiv solunar periode', bd_solunar_hint:'Månens position bestemmer fiskenes aktivitetscyklus',
    sol_major_word:'major', sol_minor_word:'minor', sol_tag_hint:'periode — fiskene er markant mere aktive',
    bd_timeofday:'Tidspunkt', bd_timeofday_none:'Ingen særlig dag-aktivitet', bd_timeofday_hint:'Tidspunkt relativt til solopgang/solnedgang',
    bd_cloud:'Skydække', cloud_word:'skydække', bd_cloud_hint:'Overskyet (>65%) giver +8 — fisk jager friere i diffust lys',
    tag_overcast:'☁ Overskyet', cloud_tag_hint:'fisk jager mere aktivt',
    bd_wind:'Vind', bd_wind_hint:'Svag vind er ideelt; stærk vind gør fiskeri vanskeligt',
    tag_wind_light:'💨 Svag vind', wind_light_word:'Svag vind', wind_ideal:'ideelle forhold',
    tag_wind_strong:'💨 Stærk vind', wind_strong_word:'Stærk vind', wind_difficult:'vanskelige forhold',
    bd_precip:'Nedbør', precip_word:'nedbørschance', bd_precip_hint:'>70% = tordenvejrsrisiko, straffer hårdt',
    tag_thunder:'🌧 Risiko for tordenvejr', thunder_tag_hint:'tordenvejrsrisiko, kulfiberstænger tiltrækker lyn!',
    bd_windtrend:'Vindtrend', windtrend_worse:'Stigende vind forværrer betingelserne gradvist', windtrend_better:'Aftagende vind forbedrer betingelserne',
    windtrend_tag_rising:'Vinden stiger', windtrend_tag_falling:'Vinden aftager',
    windtrend_over3h:'m/s over 3 timer — betingelserne', windtrend_worsen:'forværres', windtrend_improve:'forbedres',
    bd_winddir:'Vindretning', wind_suffix:'-vind', bd_winddir_hint:'V/VNV = bedst; NØ/Ø = ugunstig (gammel fiskeviden)',
    unfavourable:'ugunstig', winddir_tag_hint:'anses traditionelt for ugunstig for fiskeri',
    bd_wave:'Bølgehøjde', wave_word:'bølger', wave_height_word:'bølgehøjde',
    wave_danger:'Farlig sø', wave_high:'Høj sø', wave_calm_lbl:'Blik',
    wave_danger_hint:'farlige forhold, frarådes kraftigt', wave_high_hint:'vanskelige betingelser',
    wave_care_hint:'let forsigtighed anbefales ved vadefiskeri', wave_calm_hint:'næsten blikstille, ideelt for alle metoder',
    bd_method:'Fiskemetode', at_word:'ved', bd_method_hint:'Ekstra vægtning for valgt fiskemetode',
    bd_tide:'Tidevand', tide_rising_word:'↑ Stigende', tide_falling_word:'↓ Faldende', tide_none:'Ingen tidevand',
    bd_tide_hint:'Stigende tidevand aktiverer kystfisk markant',
    tide_tag_rising:'Stigende tidevand ved', tide_tag_falling:'Faldende tidevand ved',
    tide_activates:'aktiverer kystfisk', tide_moderate:'moderat aktivitet',
    bd_moon:'Månefase', bd_moon_hint:'Ny- og fuldmåne giver ekstra aktivitet',
    bd_lightning:'Lynrisiko', thunder_risk:'Tordenvejrsrisiko', bd_lightning_hint:'Høj nedbørschance = mulig tordenvejr, ekstra straf',
    bd_species_hint:'Betingelserne matcher dine valgte målartes præferencer',
    // Score-breakdown explanations (shown as a bullet list in the modal)
    bd_why_title:'Hvorfor disse point?',
    bd_base_why:'Hvert tidsvindue starter på 20 basispoint.',
    bd_pressure_why:'Stigende lufttryk udløser aktiv ædelyst; faldende tryk dæmper den. En af de stærkeste faktorer (op til ±25).',
    bd_solunar_why:'Sol- og måneperioder hvor fisk erfaringsmæssigt æder mest — en “major”-periode kan give op til +18.',
    bd_timeofday_why:'Daggry og skumring er de bedste tidspunkter; midt på dagen trækker fra.',
    bd_cloud_why:'Overskyet dagslys får rovfisk til at jage friere i det diffuse lys (+8).',
    bd_wind_why:'Let vind giver liv i vandet (+7); hård vind over 8 m/s gør fiskeriet svært (−18).',
    bd_windtrend_why:'Aftagende vind forbedrer forholdene; tiltagende vind forværrer dem.',
    bd_winddir_why:'Gammel fiskeviden: vestlige vinde fisker bedst, østlige dårligst — kun en mindre justering (±2–5).',
    bd_precip_why:'Let regn kan aktivere fisk (+4); over 70 % nedbør betyder tordenrisiko og straffer hårdt (−20).',
    bd_lightning_why:'Tordenvejr eller lyn i nærheden — farligt, og fiskene søger dybt.',
    bd_wave_why:'Let bølgegang (0,1–0,5 m) er ideelt; høje bølger over 1 m er både dårlige og farlige (−12 til −20).',
    bd_method_why:'Justering for din valgte metode (kyst/waders/båd) i forhold til bølgehøjden.',
    bd_moon_why:'Månefasen påvirker den generelle aktivitet — ny- og fuldmåne er stærkest.',
    bd_tide_why:'Tidevandsbevægelse — især stigende vand — er en stærk udløser for kystfisk (+5 til +12).',
    fac_species_name_why:'Bonus når forholdene rammer dine valgte målarters foretrukne betingelser (op til +25).',
    fac_spot_name_why:'Bonus når pladsen har dine målarter aktive i denne måned.',
    // Toasts / connectivity
    toast_fetch_failed:'Kunne ikke hente vejrdata til', toast_retry:'Prøv igen',
    toast_sync_failed:'Kunne ikke synkronisere til din konto — ændringer er gemt lokalt',
    toast_offline:'Du er offline — vejrdata kan ikke hentes', toast_back_online:'Online igen — opdaterer vejrdata…',
    toast_refreshing_stale:'Opdaterer forældede vejrdata…',
    // Setup sharing
    setup_share_btn:'📤 Del min opsætning', setup_link_copied:'✓ Link kopieret — send det til en fiskemakker',
    setup_shared_title:'Delt opsætning', setup_shared_intro:'En anden FishCast-bruger har delt deres opsætning med dig:',
    setup_import:'Importér opsætning', setup_import_warn:'Erstatter dine nuværende lokationer, målarter og tidsvinduer.',
    setup_sum_locs:'lokationer', setup_sum_species:'målarter', setup_sum_slots:'tidsvinduer',
    topbar_species:'🎯 Målarter', topbar_locations:'📍 Lokationer', topbar_times:'⏱ Tidsvinduer',
    save_back_dash:'Gem og tilbage til dashboard',
    // Score labels
    score_excellent:'Fremragende', score_good:'Godt', score_avg:'Middel',
    score_below:'Under middel', score_poor:'Dårligt',
    // Score info modal
    score_modal_title:'📊 Fiskeindeks — forklaring',
    score_modal_base:'Basisværdi for alle vinduer',
    score_breakdown_title:'Score-fordeling bedste time:',
    score_tip:'💡 Tilvælg målarter for at justere scoren til de valgte arters præferencer.',
    // Wind trend labels
    wind_rising_fast:'↑↑ Tiltagende kraftigt',
    wind_rising:'↑ Tiltagende',
    wind_falling_fast:'↓↓ Aftager kraftigt',
    wind_falling:'↓ Aftager',
    wind_stable:'→ Stabilt',
    // Pressure trend labels
    press_rising_fast:'Stigende kraftigt ↑↑',
    press_rising:'Svagt stigende ↑',
    press_stable:'Stabilt →',
    press_falling:'Svagt faldende ↓',
    press_falling_fast:'Faldende kraftigt ↓↓',
    press_fish_rising_fast:'📈 Hurtigt stigende tryk — fiskene aktiveres kraftigt og jager aggressivt. Et af de bedste tidsvinduer til kystfiskeri.',
    press_fish_rising:'📈 Stigende tryk — fiskenes aktivitet tiltar. Forventede gode bid, særligt i starten af stigningen.',
    press_fish_stable:'➡️ Stabilt tryk — fiskene har tilpasset sig og holder til på kendte dybder. Fiskeri er forudsigeligt, men ingen ekstra aktivitetspeak.',
    press_fish_falling:'📉 Faldende tryk — fiskene mærker det og fodrer aktivt inden trykket rammer bunden. Fang dem nu, mens de stadig er oppe.',
    press_fish_falling_fast:'📉 Kraftigt faldende tryk — fiskene trækker sig til bunden. Forvent sværere fiskeri; de fleste arter holder lav profil.',
    // Tide labels
    tide_rising:'🌊 Stigende tidevand',
    tide_falling:'🌊 Faldende tidevand',
    // Conditions tab
    cond_temp:'Temperatur', cond_wind:'Vind', cond_gust:'Vindstød', cond_pressure:'Lufttryk',
    cond_cloud:'Skydække', cond_precip:'Nedbørschance',
    safety_title:'🦺 Sikkerhed & metode', safety_undercurrent:'Underdrift', sm_boat:'🚢 Båd', sm_shore:'🎣 Kyst', sm_wader:'🦺 Vadefiskeri',
    rec_boat_ideal:'Ideelt for lille båd', rec_boat_good:'Godt for båd', rec_boat_caution:'Vær forsigtig', rec_boat_no:'Bliv i land',
    rec_shore_good:'God fra kyst', rec_shore_instead:'Fisk fra kyst i stedet', rec_shore_caution:'Vær forsigtig', rec_shore_no:'Undgå eksponerede kyster',
    rec_wader_ideal:'Ideelt til vadefiskeri', rec_wader_good:'God til vadefiskeri', rec_wader_caution:'Med forsigtighed', rec_wader_mud:'Mudderbund — vad ikke', rec_wader_undercurrent:'Kraftig underdrift — ikke sikkert', rec_wader_waves:'Bølger for høje',
    rec_note_mud:'🚫 Mudderbund — risiko for at synke fast', rec_note_slip:'⚠️ Glat bund — skridsikre sko + stav', rec_note_undercurrent_strong:'🚫 Kraftig underdrift — fald- og understrømsrisiko', rec_note_undercurrent_mod:'⚠️ Moderat underdrift — brug vadevandsstav', rec_note_slip_waves:'⚠️ Glat bund + bølger — forhøjet faldrisiko', rec_note_sand_weever:'⚠️ Fjæsinger i sandet om sommeren — vad forsigtigt',
    uc_negligible:'ubetydelig', uc_low:'lav', uc_moderate:'moderat', uc_strong:'kraftig',
    bft_0:'Stille', bft_1:'Svag luftning', bft_2:'Svag brise', bft_3:'Let brise', bft_4:'Jævn brise',
    bft_5:'Frisk brise', bft_6:'Hård vind', bft_7:'Stiv kuling', bft_8:'Hård kuling', bft_9:'Stormende kuling',
    bft_10:'Storm', bft_11:'Stærk storm', bft_12:'Orkan',
    cond_wave:'Bølgehøjde', cond_period:'Bølgeperiode', cond_swell:'Dønning',
    cond_tide:'Tidevand', cond_tide_from:'Tidevand fra',
    wave_forecast:'📈 Bølgeprognose',
    // Spot finder
    sf_lucky_badge:'🎲 Held og lykke', sf_nearby_badge:'📍 Find i nærheden',
    topbar_finder:'🔍 Find pladser', sf_finder_title:'🔍 Find fiskepladser', or:'eller',
    lgt_danger:'fisk ikke!', lgt_warning:'overvej at stoppe', lgt_caution:'hold øje',
    tide_station:'Tidevandsstation', tide_dist:'km væk',
    sf_targeting:'Søger efter:', sf_targeting_all:'alle arter', sf_edit_species:'Skift arter',
    sf_search_geo_ph:'By, sted eller postnummer…', sf_use_saved:'Eller vælg en gemt lokation:',
    sf_results_count:'pladser fundet', sf_pick_point:'Vælg et startpunkt for at søge',
    sf_score_cap:'Egnethed', sf_score_note:'Score = hvor egnet pladsen er til dine arter i denne måned (uafhængig af vejret). Dashboardets score viser derimod de aktuelle vejrforhold i dit tidsvindue.',
    sf_when:'🗓 Hvornår vil du ud og fiske?',
    sf_date:'Dato', sf_time:'Tidspunkt', sf_radius:'Radius',
    sf_from_where:'Fra hvor?',
    sf_geo_ph:'By, sted eller postnummer...',
    sf_search_btn:'📍 Find fiskepladser',
    sf_search_lucky:"🎲 Find Danmarks bedste spots",
    sf_no_results:'Ingen pladser fundet i denne radius.',
    sf_results_nearby:'Fiskepladser inden for',
    sf_results_km:'km',
    sf_add_to_locs:'+ Tilføj til mine lokationer',
    sf_goto_dash:'Gå til dashboard →',
    sf_use_location:'📍 Brug min placering',
    sf_searching:'Søger...',
    sf_dist:'km væk',
    sf_no_windows:'Ingen tidsvinduer',
    // Lure colors
    lure_silver:'Sølv', lure_pearl:'Perlemorshvid', lure_gold:'Guld',
    lure_chartreuse:'Chartreuse', lure_orange:'Orange', lure_red:'Rød',
    lure_firetiger:'Firetiger', lure_uvwhite:'UV-hvid', lure_green:'Grøn',
    lure_black:'Sort', lure_pink:'Pink',
    lure_reason_silver:'Klart vand + sol — naturlig blink',
    lure_reason_pearl:'Klart vand + sol — subtilt blinkende',
    lure_reason_gold:'Delvist overskyet — varm flash',
    lure_reason_chartreuse:'Overskyet / diffust lys — høj synlighed',
    lure_reason_orange:'Grumset vand / stærk vind — kontrastfarve',
    lure_reason_red:'Mørkt / grumset vand — maks kontrast',
    lure_reason_firetiger:'Høje bølger / silt — voldsom kontrast',
    lure_reason_uvwhite:'Lavt lys / morgen-aften — lyser op',
    lure_reason_green:'Grumset ferskvand — mimetisk',
    lure_reason_black:'Meget grumset / nat — silhuet-kontrast',
    lure_reason_pink:'Klart saltvandsforhold — havørred-favorit',
    lure_tip_murky:'Grumset vand: brug store, kraftige farver og langsommere bevægelse',
    lure_tip_lowlight:'Lavt lys: UV-hvid og chartreuse reflekterer diffust lys bedst',
    lure_tip_clear:'Klart stille vand: naturlige subtile farver — fiskene er sky',
    lure_tip_overcast:'Overskyet: mellemstærke attractor-farver virker godt i diffust lys',
    // Species tackle tips
    tip_hornfisk:'🐟 Hornfisk: brug silketråd eller små tripler på en dropper-line efter blinket — hornfisken hugger short',
    tip_gedde:'🐊 Gedde: brug stålfortom — geddens tænder skærer monofilament over',
    tip_sandart:'🐊 Sandart: langsom bundjigging 0.5–1.5 m over bunden — kræver tålmodighed',
    tip_aborre:'🐡 Aborre: drop-shot eller micro-jig 3–8 g — reagerer godt på langsom animation',
    tip_torsk:'🐡 Torsk: tung pilker 40–150 g afhængig af dybde og strøm — bund-rig med orm virker også',
    tip_havørred:'🐟 Havørred: blink, wobler eller flue langs bræmmer og stenrev — tidlig morgen bedst',
    tip_laks:'🐟 Laks: brug kraftig fortom (20–30 lb) og store wobler/spinners — fisk i strømmende vand',
    tip_al:'🐍 Ål: orm eller død agnfisk på bunden nat-fiskeri — fisk stille med slap linje',
    tip_makrel:'🐟 Makrel: sølv-sluk eller feathered jig i hurtig bevægelse — find stimerne visuelt',
    tip_fjaesing:'☠️ Fjæsing: vadefisk — ALTID vandsko/vadesko. Stikket er smertefuldt, nedsænk i varmt vand (45°C)',
    // Moon phases (from solunar.js)
    moon_new:'Nymåne', moon_waxing_crescent:'Tiltagende halvmåne',
    moon_first_quarter:'Første kvarter', moon_waxing_gibbous:'Tiltagende',
    moon_full:'Fuldmåne', moon_waning_gibbous:'Aftagende',
    moon_last_quarter:'Sidste kvarter', moon_waning_crescent:'Aftagende halvmåne',
    // Solunar periods
    solunar_major:'🌕 Majortid', solunar_minor:'🌙 Minortid',
    solunar_golden:'Gode fisketider:', solunar_none:'Ingen solunar periode i dette vindue',
    // Week sparkline
    best_day_week:'Bedste dag:', week_overview:'Ugeoversigt',
    // Water temperature
    water_temp:'Vandtemp.',
    // Conditions tab labels
    cond_beaufort:'Beaufort', cond_wind_trend:'Vindtrend',
    // Favourite spots
    fav_add:'Tilføj til favoritter', fav_remove:'Fjern fra favoritter',
    // Spot notes
    note_placeholder:'Tilføj note til dette sted…',
    note_label:'📝 Note', note_save:'Gem', note_saved:'✓ Gemt',
    // Stale data
    stale_banner:'Data fra', stale_banner2:'— kan være forældet.',
    stale_update:'Opdater nu',
    // Map & pin popup
    map_your_locs:'Dine lokationer', map_official:'Officielle pladser', map_click_new:'Klik for ny',
    map_score_today:'Score i dag', map_score_legend:'farve = dagens score',
    map_back_list:'Lokationsliste',
    map_show_all:'Vis alle pladser',
    map_instructions:'🖱 Klik på kortet for at placere et nyt fiskested. Grønne cirkler = officielle pladser fra fishingindenmark.info.',
    pin_loading:'⏳ Henter stedsdata…', pin_new:'📌 Nyt fiskested', pin_name:'Navn',
    pin_wt:'Vandtype', pin_auto:'(auto-detekteret)', wt_mixed_opt:'🗺 Blandet',
    no_locations:'Ingen lokationer.',
    loc_empty_title:'Ingen fiskepladser endnu',
    loc_empty_sub:'Søg efter et sted ovenfor, eller vælg det direkte på kortet.',
    drag_handle:'Træk for at omarrangere', move_up:'Flyt op', move_down:'Flyt ned',
    search_loc_label:'Søg efter lokation',
    spots_add_hint:'Klik + Tilføj på et spot for at tilføje det til dine fiskepladser',
    // Spot finder time step
    sf_lucky_sub:'Bedste hotspot i Danmark', sf_nearby_sub:'Søg fra et bestemt sted',
    date_today:'I dag', date_tomorrow:'I morgen', sf_pick_date:'Vælg dato',
    tp_early:'🌅 Tidlig morgen', tp_forenoon:'🌤 Formiddag', tp_afternoon:'☀️ Eftermiddag', tp_evening:'🌇 Aften',
    sf_next_species:'Næste: Vælg art →', sf_next_start:'Næste: Vælg startsted →',
    sf_geo_start_ph:'Søg by eller sted som startpunkt…',
    // Fjæsing venom banners
    venom_sel_title:'Fjæsing valgt — vigtig advarsel:',
    venom_sel_body:'Giftige pigge — brug tang ved håndtering. Ved stik: varmt vand 45–50°C i 30–60 min.',
    venom_tab_title:'Giftadvarsel — Fjæsing:',
    venom_tab_body:'Fjæsingen har giftige pigge på rygfinnen og gællelågene. Den graver sig ned i sandbunden med pigge opad og er svær at se — særlig farlig for vadefiskere på sandstrande.',
    venom_sting:'Ved stik:', venom_sting_body:'Nedsænk straks i så varmt vand du tåler (45–50°C) i 30–60 min — varmen nedbryder giften. Søg læge ved alvorlig reaktion eller tegn på infektion.',
    venom_handling:'Håndtering:', venom_handling_body:'Brug altid fiskepincet/tang. Skær pigge af med saks inden rensning.',
    warn_hint:'Klik for at se regler og advarsler',
    render_error:'Noget gik galt under visningen. Genindlæs siden — dine data er gemt.',
    // Auth (v2)
    auth_login:'Log ind', auth_logout:'Log ud', auth_signup:'Opret konto',
    auth_email:'E-mail', auth_password:'Adgangskode (min. 6 tegn)',
    auth_have_account:'Har du allerede en konto?', auth_no_account:'Ingen konto endnu?',
    auth_check_email:'✓ Tjek din e-mail for at bekræfte kontoen, og log derefter ind.',
    loc_remove:'Fjern lokation',
    auth_forgot:'Glemt adgangskode?', auth_reset_title:'Nulstil adgangskode', auth_reset_intro:'Indtast din e-mail, så sender vi et link til at nulstille din adgangskode.',
    auth_reset_send:'Send nulstillingslink', auth_reset_sent:'✓ Tjek din e-mail for et link til at nulstille adgangskoden.', auth_back_login:'Tilbage til log ind',
    auth_new_password_title:'Vælg ny adgangskode', auth_new_password:'Ny adgangskode (min. 6 tegn)', auth_update_password:'Opdater adgangskode', auth_password_updated:'✓ Adgangskode opdateret — du er logget ind.',
    auth_why:'Med en konto synkroniseres dine lokationer, målarter og tidsvinduer på tværs af enheder.',
    auth_local_note:'Kører uden konto — alt gemmes kun lokalt i denne browser.',
    welcome_v2_sub:'Din personlige fiskeassistent — nu i Vue.', welcome_no_setup:'find pladser uden opsætning',
    setup_start:'Start opsætning →', goto_dash:'Gå til dashboard →',
    quick_start:'⚡ Hurtig start', quick_start_sub:'Find pladser nær dig og kom straks i gang', quick_start_busy:'⏳ Finder pladser nær dig…',
    // Condition delta
    vs_yesterday:'vs. i går',
    // Wind relative to shore
    wind_onshore:'Pålandsvind', wind_offshore:'Aflandsvind',
    wind_cross_onshore:'Tværvind (ind)', wind_cross_offshore:'Tværvind (ud)',
    wind_shore_label:'Kystretning:',
    // Tide arrows on window cards
    tide_up:'↑ Stigende', tide_down:'↓ Faldende',
    // Min size / bag limit on species cards
    sp_min_size:'Min.', sp_bag_limit:'Dagskvoter:', sp_cr:'♻️ C&R anbefalet',
    // Pressure graph
    pressure_graph:'Lufttryk — 48 timer', pressure_hpa:'hPa',
    // Share
    share_btn:'🔗 Del', share_copied:'✓ Kopieret!', share_window:'Delt fiskevindue', share_setup_btn:'🔗 Del opsætning',
    share_add_loc:'+ Tilføj lokation', share_view_dash:'Gå til dashboard →',
    share_intro:'En anden FishCast-bruger har delt dette vindue med dig:',
    // Notifications
    notif_enable:'🔔 Påmindelser', notif_enabled:'🔔 Aktiv',
    notif_denied:'Notifikationer blokeret', notif_scheduled:'Påmindelser planlagt',
    notif_title:'🎣 FishCast — Godt vindue snart!',
    notif_none:'Ingen kommende vinduer at minde om',
    // Quick reset
    reset_data_btn:'🗑 Ryd vejrdata', reset_data_confirm:'Ryd alle gemte vejrdata? Lokationer og indstillinger beholdes.',
    reset_choices_btn:'↺ Nulstil arter & tider', reset_choices_confirm:'Nulstil målarter og tidsvinduer? Lokationer beholdes.',
    data_footer:'Data', pressure_48h:'Lufttryk 48t', wave_24h:'Bølger 24t',
    reset_data_ok:'✓ Data ryddet',
  },
  en: {
    // General
    back:'← Back', next:'Next →', skip:'Skip →', close:'Close',
    add:'+ Add', added:'✓ Added', save:'Save', cancel:'Cancel',
    reset_btn:'🔄 Reset everything',
    reset_confirm:'Reset all — locations, time windows and target species will be deleted. Are you sure?',
    show_on_map:'Show on map 🗺', rename:'Rename',
    update_all:'⟳ Update all data', data_ok:'✓ Data',
    updated_prefix:'Updated', time_just_now:'just now', time_min_ago:'min ago', time_hr_ago:'h ago',
    cal_title:'Fishing trip', cal_score:'Score', cal_add:'Add to calendar',
    dlg_confirm:'Confirm', dlg_cancel:'Cancel',
    topbar_log:'📒 Catch log', log_title:'Catch log',
    log_add:'Log a catch', log_date:'Date', log_species:'Species', log_species_other:'Other / unknown',
    log_location:'Location', log_location_ph:'Where did you catch it?',
    log_length:'Length (cm)', log_weight:'Weight (kg)', log_notes:'Notes', log_notes_ph:'Bait, weather, method…',
    log_optional:'· optional', log_not_measured:'not measured', log_count:'Quantity',
    log_save:'Save catch', log_empty_title:'No catches yet', log_empty_sub:'Log your first catch above.',
    log_total:'catches', log_remove:'Delete catch', log_remove_confirm:'Delete this catch?',
    log_edit:'Edit', log_edit_h:'Edit catch', log_update:'Update catch', log_cancel:'Cancel',
    log_stat_catches:'Catches', log_stat_longest:'Longest', log_stat_heaviest:'Heaviest', log_stat_top:'Top species',
    log_outcome:'Kept or released?', log_kept:'Kept', log_released:'Released', log_stat_released:'Released',
    log_time:'Time', log_score_btn:'⚡ Calculate bite-score', log_score_label:'Bite-score', log_scoring:'Calculating…', log_score_na:'No data for that time',
    guard_undersize:'Below minimum size: {len} cm < {min} cm', guard_closed:'Possibly in a closed season on this date — check the rules',
    insight_title:'Model check', insight_run:'Analyse catches', insight_avg:'Avg. bite-score when you caught',
    insight_sub:'Compares the model\'s score with when you actually caught fish. {n} catches can be analysed (needs a time + a saved location).',
    insight_dist:'Distribution of bite-scores at catch time',
    insight_thin:'Too few catches to say anything meaningful yet — log more with a time and location.',
    insight_strong:'Most of your catches happened in good windows — the model appears to match your fishing.',
    insight_mixed:'Mixed picture: you catch in both good and poorer windows. Treat the model as an indication, not a guarantee.',
    insight_weak:'Your catches mostly happen in low-scoring windows — the model doesn\'t fit your fishing well (or you mostly fish at difficult times).',
    loading:'Loading…', error:'Error', details:'Details',
    // Days
    day0:'Sun',day1:'Mon',day2:'Tue',day3:'Wed',day4:'Thu',day5:'Fri',day6:'Sat',
    // Months
    month0:'Jan',month1:'Feb',month2:'Mar',month3:'Apr',month4:'May',month5:'Jun',
    month6:'Jul',month7:'Aug',month8:'Sep',month9:'Oct',month10:'Nov',month11:'Dec',
    // Welcome
    welcome_tagline:'Your personal fishing assistant.',
    welcome_sub:'Set your locations and time slots — we find the best window.',
    welcome_setup:'Set up my fishing spots →',
    welcome_continue:'Continue to dashboard',
    welcome_or:'or',
    welcome_shortcut:'Find fishing spots fast — no setup needed',
    welcome_lucky_title:'Lucky Cast',
    welcome_lucky_sub:"Find Denmark's best hotspot for a specific species",
    welcome_nearby_title:'Find Nearby',
    welcome_nearby_sub:'Search fishing spots within a given distance from you',
    attribution:'Weather: Open-Meteo · Tides + Lightning: DMI Open Data · Regulations: lfst.dk',
    // Availability
    avail_title:'When can you fish?',
    avail_sub:'Set your available time windows',
    avail_window:'Time Window',
    avail_add:'+ Add time window',
    avail_notice:'ℹ️ Add at least one time window to continue.',
    avail_time_warn:'End time must be after start time', avail_days_warn:'Select at least one day',
    avail_fix_before_next:'Fix the time slot above before continuing — a slot that ends before it starts can’t be scored.',
    time_from:'From', time_to:'To',
    method_label:'Fishing method', method_pick:'Select one or more',
    method_required:'At least one method must be selected',
    method_shore:'Shore', method_waders:'Waders', method_boat:'From boat',
    fm_shore_hint:'Shore fishing / rod fishing from land',
    fm_waders_hint:'Wading — bottom type and undercurrent weighted',
    fm_boat_hint:'Boat trip — wave height and wind weighted harder',
    next_species:'Next: Target species →',
    next_choose_art:'Next: Choose species →',
    next_choose_start:'Next: Choose start location →',
    edit_time:'Edit →',
    // Water type
    wt_title:'What type of fishing water?',
    wt_sub:'Choose the water types you primarily fish in',
    wt_fact_hd:'Did you know?',
    wt_fact_body:"Most of Denmark's coast is <em>brackish</em> — not true saltwater. Kattegat, Øresund, the Danish straits and the Baltic Sea are all mixtures of salt and freshwater. Only the North Sea (Jutland's west coast) is true ocean. This means freshwater fish like pike and perch can live in many Danish harbours and fjords.",
    wt_most_dk:'Most common in DK',
    wt_fresh_label:'Freshwater', wt_fresh_sub:'Lakes, rivers and streams',
    wt_brackish_label:'Brackish', wt_brackish_sub:'Fjords, straits, Baltic Sea',
    wt_salt_label:'Saltwater', wt_salt_sub:'North Sea (west coast)',
    wt_both_label:'All water', wt_both_sub:'All water types',
    wt_salt_hint:'North Sea / true saltwater (~30–35 ppt)',
    wt_brackish_hint:'Kattegat, Øresund, Straits, Baltic Sea (~5–25 ppt). Mix of salt & freshwater species.',
    wt_fresh_hint:'Lakes, rivers and streams (~0 ppt)',
    wt_both_hint:'Varying water type — see spot description',
    wt_salt_label_full:'🌊 Saltwater',
    wt_brackish_label_full:'🌿 Brackish',
    wt_fresh_label_full:'💧 Freshwater',
    wt_both_label_full:'🗺 Mixed',
    wt_override:'Click to override water type',
    wt_override_warn:'⚠️ Overriding official data',
    // Locations
    loc_title:'Your fishing locations',
    loc_sub:'Search, browse official spots, or click directly on the map',
    loc_search_tab:'Search & Browse', loc_map_tab:'Map',
    loc_search_ph:'E.g. Køge, Esbjerg, Silkeborg...',
    loc_popular:'⭐ Popular fishing spots', loc_nearby_hd:'📍 Fishing spots nearby',
    loc_db_count:'spots in database',
    loc_empty:'No locations added yet',
    loc_official:'🎣 Official fishing spot', loc_custom:'📌 Custom spot',
    loc_brackish_note:'🌿 Brackish — both salt & freshwater species possible ℹ️',
    loc_in_season:'No active species this month',
    // Species
    sp_title:'Which species are you targeting?',
    sp_sub:'Choose your target species — the score adapts to their preferences',
    sp_show:'Show fishing conditions →',
    sp_lucky_btn:'🎲 Find best hotspot',
    sp_high_season:'⭐ Peak season now',
    sp_in_season:'✅ In season now', sp_restricted:'⚠️ With restrictions', sp_closed:'🚫 Closed season',
    sp_banned_label:'Catch banned', sp_restricted_label:'Restrictions',
    sp_handle:'Use pliers when handling',
    sp_regs_note:'⚠️ Regulations are advisory. Always verify at',
    // Dashboard
    dash_best:'🏆 Best window',
    dash_targets:'🎯 Target species:',
    dash_no_windows:'No time windows found. Add availability in the setup.',
    dash_no_forecast:'No weather data — press Update',
    tab_windows:'📅 Time windows', tab_seasons:'🐟 Fishing seasons', tab_conditions:'🌤 Weather & Waves',
    best_hour:'Best hour:',
    lure_label:'🎨 Lure:',
    your_locs:'📍 Your locations',
    moon_title:'🌙 Moon phase today',
    lightning_title:'⚡ Lightning status',
    no_lightning:'No lightning detected',
    update_lightning:'⟳ Update lightning',
    lightning_src:'Source: DMI · Last 45 min · Danish lightning only',
    lightning_checked:'Checked',
    explanation:'ℹ️ Explanation',
    sunrise:'Sunrise', sunset:'Sunset',
    moonrise:'Moonrise', moonset:'Moonset', culmination:'Culmination',
    moon_phase_today:'Phase:',
    moon_tip_new:'🌑 New moon — tides are at their strongest (spring tide). Fish are highly active; the best solunar periods align with sunrise and sunset.',
    moon_tip_full:'🌕 Full moon — peak solunar effect. Spring tides create strong currents and active fish. Night fishing can be exceptional.',
    moon_tip_quarter:'🌓 Quarter moon — neap tide with weaker currents. Fish are less active than at new/full moon, but solar periods still produce bites.',
    moon_tip_gibbous:'🌔 Gibbous moon — approaching peak. Activity is building as the lunar cycle nears its strongest point — fishing improves day by day.',
    no_windows_empty:'No time windows. Check your availability.',
    no_locs_empty:'No locations.',
    data_missing:'No weather data',
    load_data_btn:'Fetch weather', load_data_for:'Fetch data for', load_data_missing:'locations missing weather data',
    // Hardcoded strings
    locs_ready:'locations ready', locs_failed:'failed',
    invalid_window:'Invalid time window',
    no_official_spots:'No official fishing spots within 40 km',
    wt_salt_opt:'🌊 Saltwater (~33 ppt)', wt_brackish_opt:'🌿 Brackish (fjords, straits, Baltic)', wt_fresh_opt:'💧 Freshwater (lakes, rivers)',
    lightning_strikes_near:'strikes within',
    sf_no_spots_found:'No spots found', sf_no_spots_db:'in the database', sf_no_spots_radius:'within',
    sf_try_broader:'Try a broader search, or add your location manually via 📍 Locations → Map.',
    sf_score_hint:'Spot score based on species, season and habitat — weather data loads after you add the spot',
    score_lightning_name:'Lightning safety', score_lightning_desc:'Active lightning within 10 km caps the score at 15 and shows a red warning. Carbon rods conduct lightning — never fish in a storm.',
    // Score modal factors
    fac_pressure_name:'Pressure trend', fac_pressure_desc:'Rising pressure → fish activate and hunt actively. Falling pressure → they retreat to the bottom. The single most important factor.',
    fac_solunar_name:'Solunar periods', fac_solunar_desc:'Lunar culmination (overhead/underfoot) gives the biggest activity periods. Major periods = +30 points, minor (rise/set) = +15.',
    fac_timeofday_name:'Time of day', fac_timeofday_desc:'Dawn (±1h sunrise) is best (+20). Dusk is second best (+15). Midday is penalized (−10). Night fishing is neutral.',
    fac_tide_name:'Tide', fac_tide_desc:'Saltwater only. A rising tide markedly activates coastal fish. Sourced from DMI\'s official tide data for the nearest station.',
    fac_wave_name:'Wave height', fac_wave_desc:'< 0.3m: ideal (+5). 0.6–1m: penalty (−6). > 1m: heavy penalty. Species like turbot prefer light wave action — adjusted by target species.',
    fac_wind_name:'Wind', fac_wind_desc:'Light wind (< 3 m/s) gives +7. Above 8 m/s gives −18. Increasing wind is penalized extra. Direction also matters (W/WNW = best).',
    fac_cloud_name:'Cloud cover', fac_cloud_desc:'Overcast (> 65%) gives +8 points. Fish are more active in diffuse light — harder to see and hunting more freely.',
    fac_precip_name:'Precipitation chance', fac_precip_desc:'> 65% precipitation chance is treated as thunderstorm risk and penalized hard (−20). Fishing with carbon rods near lightning is also discouraged.',
    fac_moon_name:'Moon phase', fac_moon_desc:'New and full moon give extra activity (+15). Quarter moon gives +5. Computed astronomically for the exact date and position.',
    fac_species_name:'Species preferences', fac_species_desc1:'Bonus for your selected target species:', fac_species_desc2:'The score increases when conditions match the species\' specific preferences.',
    fac_spot_name:'Spot relevance', fac_spot_desc:'Bonus if the fishing spot has your target species registered as active this month (from fishingindenmark.info). Official spot data.',
    score_modal_intro:'The score (0–100) combines all weather, astronomical and spot-specific factors into one easy-to-read recommendation.',
    score_modal_legend:'80+ = Excellent · 65–79 = Good · 45–64 = Average · below 45 = Poor.',
    score_breakdown_for:'📊 Actual point breakdown for:', score_total:'Total score', factor_explain:'Factor explanations',
    up_to:'up to', points:'points',
    score_modal_tip:'💡 Select target species in setup for even more precise recommendations.',
    understood:'Got it',
    // Misc UI
    species_step_notice:'ℹ️ Select no species for a general recommendation, or pick one or more for targeted scoring.',
    selected_label:'Selected:',
    no_species_selected:'None selected — searching all species',
    click_remove:'Click to remove',
    customize_open:'+ Customize ▼', customize_close:'Close ▲',
    no_active_nearby:'No active species nearby this month',
    estimate_based:'Estimate based on:', estimate_from:'Estimate from:',
    found_count:'found',
    best_hotspots:'🏆 Best hotspots',
    closed_active:'closed season active',
    // Solunar / astronomy labels
    moon_lbl_new:'New moon', moon_lbl_waxing:'Waxing', moon_lbl_quarter:'Quarter moon', moon_lbl_full:'Full moon', moon_lbl_waning:'Waning',
    sol_culm:'Lunar culmination', sol_under:'Lunar underfoot', sol_rise:'Moonrise', sol_set:'Moonset', sol_approach:'Approaching lunar period',
    tod_dawn:'Dawn (peak activity)', tod_dusk:'Dusk (good activity)', tod_night:'Night', tod_midday:'Midday (low activity)',
    // Score breakdown factors & tags
    bd_base:'Base', dash_window_avg:'Window average',
    bd_window_note:'Points are averaged across the hours in this window.',
    dash_trend:'7-day forecast for this time window',
    dash_view:'View', dash_simple:'Simple', dash_full:'Full',
    dash_horizon:'How far ahead to look', dash_h_today:'Today', dash_h_days:'days',
    tab_map:'🗺 Map', map_no_score:'No score in this range',
    maptab_hint:'Best score per spot in the selected range. Nearby spots usually share weather, so differences mostly come down to water type, bottom and shelter.',
    maptab_spread:'Spread', maptab_spread_low:'(spots look alike)', maptab_spread_high:'(spots differ)',
    maptab_compare:'Compare with nearby official spots',
    maptab_compare_loading:'Fetching weather and scoring spots…',
    maptab_compare_none:'No official spots within 30 km',
    maptab_km_away:'km away', maptab_better:'scores higher than your own spots in this range',
    dash_none_in_horizon:'No time windows in the selected range.', dash_show_week:'Show the whole week',
    dash_fetching:'Fetching new weather data…',
    conf_days:'days out', conf_med:'medium forecast confidence', conf_low:'low forecast confidence',
    conf_hint:'Forecasts get less certain further into the future',
    dash_top_pick:'Best this week', dash_showing_day:'Showing', dash_show_all_days:'Show all days',
    dash_showing:'Showing', dash_of:'of', dash_show_more:'Show more', dash_show_all:'Show all',
    map_add_cta:'Tap anywhere on the map to add a fishing spot',
    relevance_active:'target species active here',
    loc_open_map:'🗺 Pick your own spots on the map', loc_open_map_sub:'Tap the map to add any location',
    bd_pressure:'Pressure', bd_pressure_hint:'The pressure trend affects fish activity levels',
    bd_solunar:'Solunar', bd_solunar_none:'No active solunar period', bd_solunar_hint:'The moon\'s position drives the fish activity cycle',
    sol_major_word:'major', sol_minor_word:'minor', sol_tag_hint:'period — fish are markedly more active',
    bd_timeofday:'Time of day', bd_timeofday_none:'No notable daytime activity', bd_timeofday_hint:'Time relative to sunrise/sunset',
    bd_cloud:'Cloud cover', cloud_word:'cloud cover', bd_cloud_hint:'Overcast (>65%) gives +8 — fish hunt more freely in diffuse light',
    tag_overcast:'☁ Overcast', cloud_tag_hint:'fish hunt more actively',
    bd_wind:'Wind', bd_wind_hint:'Light wind is ideal; strong wind makes fishing difficult',
    tag_wind_light:'💨 Light wind', wind_light_word:'Light wind', wind_ideal:'ideal conditions',
    tag_wind_strong:'💨 Strong wind', wind_strong_word:'Strong wind', wind_difficult:'difficult conditions',
    bd_precip:'Precipitation', precip_word:'precipitation chance', bd_precip_hint:'>70% = thunderstorm risk, heavy penalty',
    tag_thunder:'🌧 Thunderstorm risk', thunder_tag_hint:'thunderstorm risk — carbon rods attract lightning!',
    bd_windtrend:'Wind trend', windtrend_worse:'Rising wind gradually worsens conditions', windtrend_better:'Falling wind improves conditions',
    windtrend_tag_rising:'Wind increasing', windtrend_tag_falling:'Wind decreasing',
    windtrend_over3h:'m/s over 3 hours — conditions', windtrend_worsen:'worsening', windtrend_improve:'improving',
    bd_winddir:'Wind direction', wind_suffix:' wind', bd_winddir_hint:'W/WNW = best; NE/E = unfavourable (old fishing wisdom)',
    unfavourable:'unfavourable', winddir_tag_hint:'is traditionally considered unfavourable for fishing',
    bd_wave:'Wave height', wave_word:'waves', wave_height_word:'wave height',
    wave_danger:'Dangerous seas', wave_high:'High seas', wave_calm_lbl:'Flat calm',
    wave_danger_hint:'dangerous conditions, strongly discouraged', wave_high_hint:'difficult conditions',
    wave_care_hint:'light caution advised when wading', wave_calm_hint:'nearly flat calm, ideal for all methods',
    bd_method:'Fishing method', at_word:'at', bd_method_hint:'Extra weighting for the chosen fishing method',
    bd_tide:'Tide', tide_rising_word:'↑ Rising', tide_falling_word:'↓ Falling', tide_none:'No tide',
    bd_tide_hint:'A rising tide markedly activates coastal fish',
    tide_tag_rising:'Rising tide at', tide_tag_falling:'Falling tide at',
    tide_activates:'activates coastal fish', tide_moderate:'moderate activity',
    bd_moon:'Moon phase', bd_moon_hint:'New and full moon give extra activity',
    bd_lightning:'Lightning risk', thunder_risk:'Thunderstorm risk', bd_lightning_hint:'High precipitation chance = possible thunderstorm, extra penalty',
    bd_species_hint:'Conditions match your selected target species\' preferences',
    // Score-breakdown explanations (shown as a bullet list in the modal)
    bd_why_title:'Why these points?',
    bd_base_why:'Every window starts at a base of 20 points.',
    bd_pressure_why:'Rising air pressure triggers active feeding; falling pressure suppresses it. One of the strongest factors (up to ±25).',
    bd_solunar_why:'Sun/moon periods when fish feed most; a “major” period can add up to +18.',
    bd_timeofday_why:'Dawn and dusk are prime times; midday counts against.',
    bd_cloud_why:'Overcast daylight lets predators hunt more freely in the diffuse light (+8).',
    bd_wind_why:'Light wind adds life to the water (+7); strong wind over 8 m/s makes fishing hard (−18).',
    bd_windtrend_why:'Falling wind improves conditions; rising wind worsens them.',
    bd_winddir_why:'Old fishing wisdom: westerly winds fish best, easterly worst — only a minor adjustment (±2–5).',
    bd_precip_why:'Light rain can activate fish (+4); over 70% precipitation means thunder risk and penalises heavily (−20).',
    bd_lightning_why:'Thunder or lightning nearby — dangerous, and fish go deep.',
    bd_wave_why:'Light chop (0.1–0.5 m) is ideal; big waves over 1 m are both poor and dangerous (−12 to −20).',
    bd_method_why:'Adjustment for your chosen method (shore/waders/boat) relative to the wave height.',
    bd_moon_why:'Moon phase nudges overall activity — new and full moon are strongest.',
    bd_tide_why:'Tidal movement — especially incoming water — is a strong trigger for coastal fish (+5 to +12).',
    fac_species_name_why:'Bonus when conditions match your target species\' preferred conditions (up to +25).',
    fac_spot_name_why:'Bonus when the spot lists your target species active this month.',
    // Toasts / connectivity
    toast_fetch_failed:'Couldn\'t load weather data for', toast_retry:'Retry',
    toast_sync_failed:'Couldn\'t sync to your account — changes are saved locally',
    toast_offline:'You\'re offline — weather data can\'t be loaded', toast_back_online:'Back online — refreshing weather…',
    toast_refreshing_stale:'Refreshing outdated weather data…',
    // Setup sharing
    setup_share_btn:'📤 Share my setup', setup_link_copied:'✓ Link copied — send it to a fishing buddy',
    setup_shared_title:'Shared setup', setup_shared_intro:'Another FishCast user shared their setup with you:',
    setup_import:'Import setup', setup_import_warn:'Replaces your current locations, target species and time slots.',
    setup_sum_locs:'locations', setup_sum_species:'target species', setup_sum_slots:'time slots',
    topbar_species:'🎯 Species', topbar_locations:'📍 Locations', topbar_times:'⏱ Time slots',
    save_back_dash:'Save and back to dashboard',
    // Score labels
    score_excellent:'Excellent', score_good:'Good', score_avg:'Average',
    score_below:'Below average', score_poor:'Poor',
    // Score info modal
    score_modal_title:'📊 Fishing index — explanation',
    score_modal_base:'Base value for all windows',
    score_breakdown_title:'Score breakdown (best hour):',
    score_tip:'💡 Select target species to adjust the score to their preferences.',
    // Wind trend labels
    wind_rising_fast:'↑↑ Increasing rapidly',
    wind_rising:'↑ Increasing',
    wind_falling_fast:'↓↓ Decreasing rapidly',
    wind_falling:'↓ Decreasing',
    wind_stable:'→ Stable',
    // Pressure trend labels
    press_rising_fast:'Rising rapidly ↑↑',
    press_rising:'Slightly rising ↑',
    press_stable:'Stable →',
    press_falling:'Slightly falling ↓',
    press_falling_fast:'Falling rapidly ↓↓',
    press_fish_rising_fast:'📈 Rapidly rising pressure — fish are feeding aggressively. One of the best windows for shore fishing.',
    press_fish_rising:'📈 Rising pressure — fish activity is building. Expect good bites, especially early in the rise.',
    press_fish_stable:'➡️ Stable pressure — fish have settled at their usual depths. Fishing is predictable but no extra activity peak expected.',
    press_fish_falling:'📉 Falling pressure — fish sense the drop and feed actively before it bottoms out. Get out while they\'re still up.',
    press_fish_falling_fast:'📉 Rapidly falling pressure — fish retreat to deeper water. Most species go quiet; expect a tough session.',
    // Tide labels
    tide_rising:'🌊 Rising tide',
    tide_falling:'🌊 Falling tide',
    // Conditions tab
    cond_temp:'Temperature', cond_wind:'Wind', cond_gust:'Gusts', cond_pressure:'Pressure',
    cond_cloud:'Cloud cover', cond_precip:'Precip. chance',
    safety_title:'🦺 Safety & method', safety_undercurrent:'Undercurrent', sm_boat:'🚢 Boat', sm_shore:'🎣 Shore', sm_wader:'🦺 Wading',
    rec_boat_ideal:'Ideal for a small boat', rec_boat_good:'Good for a boat', rec_boat_caution:'Take care', rec_boat_no:'Stay ashore',
    rec_shore_good:'Good from shore', rec_shore_instead:'Fish from shore instead', rec_shore_caution:'Take care', rec_shore_no:'Avoid exposed coasts',
    rec_wader_ideal:'Ideal for wading', rec_wader_good:'Good for wading', rec_wader_caution:'With caution', rec_wader_mud:'Mud bottom — don\'t wade', rec_wader_undercurrent:'Strong undercurrent — not safe', rec_wader_waves:'Waves too high',
    rec_note_mud:'🚫 Mud bottom — risk of getting stuck', rec_note_slip:'⚠️ Slippery bottom — non-slip shoes + staff', rec_note_undercurrent_strong:'🚫 Strong undercurrent — fall & rip risk', rec_note_undercurrent_mod:'⚠️ Moderate undercurrent — use a wading staff', rec_note_slip_waves:'⚠️ Slippery bottom + waves — higher fall risk', rec_note_sand_weever:'⚠️ Weeverfish bury in the sand in summer — wade carefully',
    uc_negligible:'negligible', uc_low:'low', uc_moderate:'moderate', uc_strong:'strong',
    bft_0:'Calm', bft_1:'Light air', bft_2:'Light breeze', bft_3:'Gentle breeze', bft_4:'Moderate breeze',
    bft_5:'Fresh breeze', bft_6:'Strong breeze', bft_7:'Near gale', bft_8:'Gale', bft_9:'Strong gale',
    bft_10:'Storm', bft_11:'Violent storm', bft_12:'Hurricane',
    cond_wave:'Wave height', cond_period:'Wave period', cond_swell:'Swell',
    cond_tide:'Tide', cond_tide_from:'Tide station',
    wave_forecast:'📈 Wave forecast',
    // Spot finder
    sf_lucky_badge:'🎲 Lucky Cast', sf_nearby_badge:'📍 Find Nearby',
    topbar_finder:'🔍 Find spots', sf_finder_title:'🔍 Find fishing spots', or:'or',
    lgt_danger:'do not fish!', lgt_warning:'consider stopping', lgt_caution:'keep watch',
    tide_station:'Tide station', tide_dist:'km away',
    sf_targeting:'Searching for:', sf_targeting_all:'all species', sf_edit_species:'Change species',
    sf_search_geo_ph:'Town, place or postcode…', sf_use_saved:'Or pick a saved location:',
    sf_results_count:'spots found', sf_pick_point:'Pick a starting point to search',
    sf_score_cap:'Match', sf_score_note:'Score = how suitable the spot is for your species this month (independent of weather). The dashboard score, by contrast, reflects the live weather conditions in your time window.',
    sf_when:'🗓 When do you want to fish?',
    sf_date:'Date', sf_time:'Time', sf_radius:'Radius',
    sf_from_where:'From where?',
    sf_geo_ph:'Town, place or postcode...',
    sf_search_btn:'📍 Find fishing spots',
    sf_search_lucky:"🎲 Find Denmark's best spots",
    sf_no_results:'No spots found within this radius.',
    sf_results_nearby:'Fishing spots within',
    sf_results_km:'km',
    sf_add_to_locs:'+ Add to my locations',
    sf_goto_dash:'Go to dashboard →',
    sf_use_location:'📍 Use my location',
    sf_searching:'Searching...',
    sf_dist:'km away',
    sf_no_windows:'No time windows',
    // Lure colors
    lure_silver:'Silver', lure_pearl:'Pearl white', lure_gold:'Gold',
    lure_chartreuse:'Chartreuse', lure_orange:'Orange', lure_red:'Red',
    lure_firetiger:'Firetiger', lure_uvwhite:'UV white', lure_green:'Green',
    lure_black:'Black', lure_pink:'Pink',
    lure_reason_silver:'Clear water + sun — natural flash',
    lure_reason_pearl:'Clear water + sun — subtle shine',
    lure_reason_gold:'Partly cloudy — warm flash',
    lure_reason_chartreuse:'Overcast / diffuse light — high visibility',
    lure_reason_orange:'Murky water / strong wind — contrast colour',
    lure_reason_red:'Dark / murky water — max contrast',
    lure_reason_firetiger:'High waves / silt — extreme contrast',
    lure_reason_uvwhite:'Low light / dawn-dusk — glows up',
    lure_reason_green:'Murky freshwater — mimetic',
    lure_reason_black:'Very murky / night — silhouette contrast',
    lure_reason_pink:'Clear saltwater — sea trout favourite',
    lure_tip_murky:'Murky water: use large, bold colours and slower retrieves',
    lure_tip_lowlight:'Low light: UV white and chartreuse reflect diffuse light best',
    lure_tip_clear:'Clear calm water: natural subtle colours — fish are wary',
    lure_tip_overcast:'Overcast: medium-strength attractor colours work well in diffuse light',
    // Species tackle tips
    tip_hornfisk:'🐟 Garfish: use silk thread or small treble hooks on a dropper-line behind the lure — garfish strike short',
    tip_gedde:'🐊 Pike: use a wire leader — pike teeth cut through monofilament',
    tip_sandart:'🐊 Zander: slow bottom jigging 0.5–1.5 m above the bottom — requires patience',
    tip_aborre:'🐡 Perch: drop-shot or micro-jig 3–8 g — responds well to slow animation',
    tip_torsk:'🐡 Cod: heavy pirk 40–150 g depending on depth and current — bottom rig with worm also works',
    tip_havørred:'🐟 Sea trout: spinner, wobbler or fly along edges and rock reefs — early morning best',
    tip_laks:'🐟 Salmon: use strong leader (20–30 lb) and large wobblers/spinners — fish in running water',
    tip_al:'🐍 Eel: worm or dead baitfish on the bottom at night — fish still with slack line',
    tip_makrel:'🐟 Mackerel: silver lure or feathered jig retrieved fast — find the schools visually',
    tip_fjaesing:'☠️ Greater Weever: wading — ALWAYS wear water shoes. The sting is painful; submerge in hot water (45°C)',
    // Moon phases (from solunar.js)
    moon_new:'New Moon', moon_waxing_crescent:'Waxing Crescent',
    moon_first_quarter:'First Quarter', moon_waxing_gibbous:'Waxing Gibbous',
    moon_full:'Full Moon', moon_waning_gibbous:'Waning Gibbous',
    moon_last_quarter:'Last Quarter', moon_waning_crescent:'Waning Crescent',
    // Solunar periods
    solunar_major:'🌕 Major period', solunar_minor:'🌙 Minor period',
    solunar_golden:'Good fishing times:', solunar_none:'No solunar period in this window',
    // Week sparkline
    best_day_week:'Best day:', week_overview:'Week overview',
    // Water temperature
    water_temp:'Water temp.',
    // Conditions tab labels
    cond_beaufort:'Beaufort', cond_wind_trend:'Wind trend',
    // Favourite spots
    fav_add:'Add to favourites', fav_remove:'Remove from favourites',
    // Spot notes
    note_placeholder:'Add a note for this spot…',
    note_label:'📝 Note', note_save:'Save', note_saved:'✓ Saved',
    // Stale data
    stale_banner:'Data from', stale_banner2:'— may be outdated.',
    stale_update:'Update now',
    // Map & pin popup
    map_your_locs:'Your locations', map_official:'Official spots', map_click_new:'Click to add',
    map_score_today:'Score today', map_score_legend:'colour = today\'s score',
    map_back_list:'Location list',
    map_show_all:'Show all spots',
    map_instructions:'🖱 Click the map to place a new fishing spot. Green circles = official spots from fishingindenmark.info.',
    pin_loading:'⏳ Loading place data…', pin_new:'📌 New fishing spot', pin_name:'Name',
    pin_wt:'Water type', pin_auto:'(auto-detected)', wt_mixed_opt:'🗺 Mixed',
    no_locations:'No locations.',
    loc_empty_title:'No fishing spots yet',
    loc_empty_sub:'Search for a place above, or pick one directly on the map.',
    drag_handle:'Drag to reorder', move_up:'Move up', move_down:'Move down',
    search_loc_label:'Search for a location',
    spots_add_hint:'Click + Add on a spot to add it to your fishing spots',
    // Spot finder time step
    sf_lucky_sub:'Denmark\'s best hotspot', sf_nearby_sub:'Search from a specific place',
    date_today:'Today', date_tomorrow:'Tomorrow', sf_pick_date:'Pick a date',
    tp_early:'🌅 Early morning', tp_forenoon:'🌤 Late morning', tp_afternoon:'☀️ Afternoon', tp_evening:'🌇 Evening',
    sf_next_species:'Next: Pick species →', sf_next_start:'Next: Pick starting point →',
    sf_geo_start_ph:'Search town or place as starting point…',
    // Fjæsing venom banners
    venom_sel_title:'Greater weever selected — important warning:',
    venom_sel_body:'Venomous spines — use pliers when handling. If stung: hot water 45–50°C for 30–60 min.',
    venom_tab_title:'Venom warning — Greater weever:',
    venom_tab_body:'The greater weever has venomous spines on its dorsal fin and gill covers. It buries itself in the sand with spines pointing up and is hard to see — especially dangerous for wading anglers on sandy beaches.',
    venom_sting:'If stung:', venom_sting_body:'Immediately immerse in water as hot as you can tolerate (45–50°C) for 30–60 min — heat breaks down the venom. Seek medical attention for severe reactions or signs of infection.',
    venom_handling:'Handling:', venom_handling_body:'Always use fishing pliers. Cut off the spines with scissors before cleaning.',
    warn_hint:'Click to see rules and warnings',
    render_error:'Something went wrong while rendering. Reload the page — your data is saved.',
    // Auth (v2)
    auth_login:'Log in', auth_logout:'Log out', auth_signup:'Create account',
    auth_email:'Email', auth_password:'Password (min. 6 characters)',
    auth_have_account:'Already have an account?', auth_no_account:'No account yet?',
    auth_check_email:'✓ Check your email to confirm the account, then log in.',
    loc_remove:'Remove location',
    auth_forgot:'Forgot password?', auth_reset_title:'Reset password', auth_reset_intro:'Enter your email and we\'ll send you a link to reset your password.',
    auth_reset_send:'Send reset link', auth_reset_sent:'✓ Check your email for a password-reset link.', auth_back_login:'Back to log in',
    auth_new_password_title:'Choose a new password', auth_new_password:'New password (min. 6 characters)', auth_update_password:'Update password', auth_password_updated:'✓ Password updated — you\'re logged in.',
    auth_why:'With an account your locations, target species and time slots sync across devices.',
    auth_local_note:'Running without an account — everything is stored locally in this browser only.',
    welcome_v2_sub:'Your personal fishing assistant — now in Vue.', welcome_no_setup:'find spots with no setup',
    setup_start:'Start setup →', goto_dash:'Go to dashboard →',
    quick_start:'⚡ Quick start', quick_start_sub:'Find spots near you and get going right away', quick_start_busy:'⏳ Finding spots near you…',
    // Condition delta
    vs_yesterday:'vs. yesterday',
    // Wind relative to shore
    wind_onshore:'Onshore wind', wind_offshore:'Offshore wind',
    wind_cross_onshore:'Crosswind (in)', wind_cross_offshore:'Crosswind (out)',
    wind_shore_label:'Shore direction:',
    // Tide arrows on window cards
    tide_up:'↑ Rising', tide_down:'↓ Falling',
    // Min size / bag limit on species cards
    sp_min_size:'Min.', sp_bag_limit:'Bag limit:', sp_cr:'♻️ C&R recommended',
    // Pressure graph
    pressure_graph:'Air pressure — 48 hours', pressure_hpa:'hPa',
    // Share
    share_btn:'🔗 Share', share_copied:'✓ Copied!', share_window:'Shared fishing window', share_setup_btn:'🔗 Share setup',
    share_add_loc:'+ Add location', share_view_dash:'Go to dashboard →',
    share_intro:'Another FishCast user shared this window with you:',
    // Notifications
    notif_enable:'🔔 Reminders', notif_enabled:'🔔 Active',
    notif_denied:'Notifications blocked', notif_scheduled:'Reminders scheduled',
    notif_title:'🎣 FishCast — Great window soon!',
    notif_none:'No upcoming windows to remind about',
    // Quick reset
    reset_data_btn:'🗑 Clear weather data', reset_data_confirm:'Clear all cached weather data? Locations and settings are kept.',
    reset_choices_btn:'↺ Reset species & times', reset_choices_confirm:'Reset target species and time slots? Locations are kept.',
    data_footer:'Data', pressure_48h:'Pressure 48h', wave_24h:'Waves 24h',
    reset_data_ok:'✓ Data cleared',
  }
};
